/**
 * Unified Question Generator Service
 * 
 * This service consolidates all question generation logic into a single, production-ready service.
 * It combines the clean architecture of CLEAN's implementation with the production features
 * from Migration's aiQuestionService.
 * 
 * Key Features:
 * - 6-step pipeline: Initialize → Generate → Evaluate → Retry → Validate → Store
 * - Quality retry logic: Up to 5 retries for questions below 80% quality threshold
 * - Diagram consistency validation: -40% penalty for missing diagrams
 * - Dynamic endpoint configuration: Supports multiple Azure OpenAI endpoints
 * - Comprehensive error handling and logging
 * 
 * Architecture: Based on ADR-47 and SPEC-47
 * Epic: #46, Feature: #47, Story: #51
 */

import { PrismaClient } from '@prisma/client'
import { getAllSubtopics, type SATSubtopic } from '@/data/sat-topics'
import { buildMathQuestionsPrompt, buildReadingQuestionsPrompt } from './questionPromptTemplates'
import { PASSAGE_LIMITS, SYSTEM_ROLES } from './promptConfig'

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

// Enriched subtopic type returned by getAllSubtopics()
type EnrichedSubtopic = SATSubtopic & { topicId: string; topicName: string; moduleType: 'reading-writing' | 'math' }

/**
 * Quality thresholds for question acceptance and regeneration
 */
const QUALITY_THRESHOLDS = {
  REGENERATION_THRESHOLD: 0.80, // Regenerate if quality ≤80%
  MAX_REGENERATION_ATTEMPTS: 5,  // Max 5 retries per question
  MIN_ACCEPTABLE_QUALITY: 0.70   // Absolute minimum to store
} as const

const READING_PASSAGE_OMISSION_MARKER = /\.\.\.|…|\[omitted\]|\(omitted\)|\[excerpt\]|abridged|truncated/i

const FULL_PASSAGE_SUBTOPICS = new Set([
  'reading comprehension',
  'main ideas and central claims',
  'supporting details and evidence',
  'inferences and implications',
  'vocabulary in context',
  'text structure and organization',
  'author s purpose and point of view',
  'authors purpose and point of view',
  'comparing texts and viewpoints',
])

/**
 * Raw question generated by LLM (before evaluation)
 */
export interface GeneratedQuestion {
  question: string
  options: string[]
  correctAnswer: number // Index of correct answer (0-based)
  explanation: string
  subtopic: string
  moduleType: 'math' | 'reading-writing'
  hasChart: boolean
  chartDescription?: string
  graphType?: string
  passage?: string
  passageTitle?: string
  passageAuthor?: string
}

/**
 * Question after Grok evaluation (adds quality metrics)
 */
export interface EvaluatedQuestion extends GeneratedQuestion {
  difficulty: 'easy' | 'medium' | 'hard'
  qualityScore: number
  isAccepted: boolean
  evaluationFeedback: string
  imageUrl?: string
  imageAlt?: string
}

/**
 * Options for question generation
 */
export interface GenerationOptions {
  mathCount?: number
  readingCount?: number
  specificTopics?: string[]
  specificSubtopics?: string[]
  specializedMode?: boolean
  moduleType?: 'math' | 'reading-writing' | 'both'
  difficulty?: 'easy' | 'medium' | 'hard' | 'mixed'
  includeImages?: boolean
  includePassages?: boolean
  storeInDatabase?: boolean
  temperature?: number
  maxTokens?: number
  enableRetry?: boolean
  enableValidation?: boolean
  skipEvaluation?: boolean
}

/**
 * Result returned by generateQuestions()
 */
export interface GenerationResult {
  questions: EvaluatedQuestion[]
  summary: {
    total: number
    accepted: number
    rejected: number
    mathCount: number
    readingCount: number
    avgQuality: number
    retryCount: number
    validationErrors: number
  }
}

/**
 * Deterministic generation plan used before LLM calls
 */
export interface GenerationPlan {
  options: Required<Pick<GenerationOptions,
    'mathCount' |
    'readingCount' |
    'moduleType' |
    'specializedMode' |
    'includeImages' |
    'includePassages' |
    'storeInDatabase' |
    'temperature' |
    'maxTokens' |
    'enableRetry' |
    'enableValidation'
  >> & Omit<GenerationOptions,
    'mathCount' |
    'readingCount' |
    'moduleType' |
    'specializedMode' |
    'includeImages' |
    'includePassages' |
    'storeInDatabase' |
    'temperature' |
    'maxTokens' |
    'enableRetry' |
    'enableValidation'
  >
  mathSubtopics: EnrichedSubtopic[]
  readingSubtopics: EnrichedSubtopic[]
}

// ============================================================================
// UNIFIED QUESTION GENERATOR CLASS
// ============================================================================

export class UnifiedQuestionGenerator {
  private prisma: PrismaClient

  constructor() {
    this.prisma = new PrismaClient()
  }

  // ==========================================================================
  // CONFIGURATION METHODS (from Migration)
  // ==========================================================================

  /**
   * Get Azure OpenAI API key from environment
   */
  private getApiKey(): string {
    return process.env.AZURE_OPENAI_API_KEY || ''
  }

  /**
   * Get chat completion endpoint URL (supports multiple configuration patterns)
   */
  private getChatEndpoint(): string {
    const directUrl = process.env.ENDPOINT_URL
    if (directUrl) return directUrl

    const base = process.env.AZURE_OPENAI_ENDPOINT
    const deployment = process.env.AZURE_OPENAI_DEPLOYMENT || process.env.DEPLOYMENT_NAME || 'gpt-4o'
    const apiVersion = process.env.AZURE_OPENAI_API_VERSION || process.env.API_VERSION || '2025-01-01-preview'

    if (!base) return ''

    if (/\/openai\/deployments\//i.test(base)) {
      return base
    }

    return `${base.replace(/\/$/, '')}/openai/deployments/${deployment}/chat/completions?api-version=${apiVersion}`
  }

  /**
   * Get Grok evaluation endpoint (falls back to chat endpoint if not configured)
   */
  private getGrokEndpoint(): string {
    return process.env.GROK_ENDPOINT || this.getChatEndpoint()
  }

  // ==========================================================================
  // MAIN ENTRY POINT: 6-STEP PIPELINE
  // ==========================================================================

  /**
   * Generate SAT questions using the 6-step pipeline:
   * 1. Initialize - Select subtopics and validate configuration
   * 2. Generate - Create raw questions via LLM
   * 3. Evaluate - Score questions with Grok
   * 4. Retry - Regenerate low-quality questions (≤80%)
   * 5. Validate - Check diagram consistency
   * 6. Store - Save to database with images
   * 
   * @param options - Generation configuration
   * @returns Generation result with questions and summary
   */
  async generateQuestions(options: GenerationOptions = {}): Promise<GenerationResult> {
    const startTime = Date.now()
    console.log('🚀 Starting 6-step question generation pipeline...')
    console.log('Options:', JSON.stringify(options, null, 2))

    const defaults: GenerationOptions = {
      mathCount: 5,
      readingCount: 5,
      specializedMode: false,
      moduleType: 'both',
      difficulty: 'mixed',
      includeImages: true,
      includePassages: true,
      storeInDatabase: true,
      temperature: 0.7,
      maxTokens: 16000,
      enableRetry: true,
      enableValidation: true,
      ...options
    }

    try {
      // Step 1: Initialize - Select subtopics
      console.log('\n📋 Step 1/6: Initialize - Selecting subtopics...')
      const plan = this.buildGenerationPlan(defaults)
      const { mathSubtopics, readingSubtopics } = plan

      // Step 2: Generate - Create raw questions
      console.log('\n🤖 Step 2/6: Generate - Creating questions with LLM...')
      const mathQuestions = defaults.mathCount! > 0 
        ? await this.generateMathQuestions(mathSubtopics, defaults) 
        : []
      const readingQuestions = defaults.readingCount! > 0 
        ? await this.generateReadingQuestions(readingSubtopics, defaults) 
        : []
      const rawQuestions = [...mathQuestions, ...readingQuestions]
      console.log(`✅ Generated ${rawQuestions.length} raw questions (${mathQuestions.length} math, ${readingQuestions.length} reading)`)

      // Step 3: Evaluate - Score with Grok
      console.log('\n🔍 Step 3/6: Evaluate - Scoring questions with Grok...')
      let evaluatedQuestions: EvaluatedQuestion[]
      if (defaults.skipEvaluation) {
        console.log('⏭️  Skipping evaluation (skipEvaluation=true) — assigning default 85% scores')
        evaluatedQuestions = rawQuestions.map(q => ({
          ...q,
          difficulty: (defaults.difficulty === 'mixed' ? 'medium' : defaults.difficulty) as 'easy' | 'medium' | 'hard',
          qualityScore: 0.85,
          evaluationFeedback: 'Evaluation skipped',
          isAccepted: true,
        }))
      } else {
        evaluatedQuestions = await this.evaluateQuestions(rawQuestions)
      }
      evaluatedQuestions = this.applyReadingPassageGuardrails(evaluatedQuestions)
      console.log(`✅ Evaluated ${evaluatedQuestions.length} questions`)

      // Step 4: Retry - Regenerate low-quality questions
      let retriedQuestions = evaluatedQuestions
      let retryCount = 0
      if (defaults.enableRetry) {
        console.log('\n🔄 Step 4/6: Retry - Regenerating low-quality questions...')
        const retryResult = await this.retryLowQualityQuestions(evaluatedQuestions, defaults)
        retriedQuestions = retryResult.questions
        retryCount = retryResult.retryCount
        console.log(`✅ Retry complete: ${retryCount} questions regenerated`)
      } else {
        console.log('\n⏭️  Step 4/6: Retry - Skipped (enableRetry=false)')
      }

      // Step 5: Validate - Check diagram consistency
      let validatedQuestions = retriedQuestions
      let validationErrors = 0
      if (defaults.enableValidation) {
        console.log('\n✅ Step 5/6: Validate - Checking diagram consistency...')
        validatedQuestions = await this.validateDiagramConsistency(retriedQuestions)
        validationErrors = validatedQuestions.filter(q => q.evaluationFeedback.includes('CRITICAL ERROR')).length
        console.log(`✅ Validation complete: ${validationErrors} errors found`)
      } else {
        console.log('\n⏭️  Step 5/6: Validate - Skipped (enableValidation=false)')
      }
      validatedQuestions = this.applyReadingPassageGuardrails(validatedQuestions)

      // Step 6: Store - Save to database
      if (defaults.storeInDatabase) {
        console.log('\n💾 Step 6/6: Store - Saving to database...')
        const questionsToStore = validatedQuestions.filter(q => q.isAccepted)
        await this.storeQuestions(questionsToStore)
        console.log(`✅ Stored ${questionsToStore.length} accepted questions`)
      } else {
        console.log('\n⏭️  Step 6/6: Store - Skipped (storeInDatabase=false)')
      }

      // Generate summary
      const accepted = validatedQuestions.filter(q => q.isAccepted)
      const rejected = validatedQuestions.filter(q => !q.isAccepted)
      const mathCount = validatedQuestions.filter(q => q.moduleType === 'math').length
      const readingCount = validatedQuestions.filter(q => q.moduleType === 'reading-writing').length
      const avgQuality = validatedQuestions.reduce((sum, q) => sum + q.qualityScore, 0) / validatedQuestions.length

      const duration = ((Date.now() - startTime) / 1000).toFixed(2)
      console.log(`\n🎉 Pipeline complete in ${duration}s`)
      console.log(`📊 Summary: ${accepted.length}/${validatedQuestions.length} accepted (${(avgQuality * 100).toFixed(1)}% avg quality)`)

      return {
        questions: validatedQuestions,
        summary: {
          total: validatedQuestions.length,
          accepted: accepted.length,
          rejected: rejected.length,
          mathCount,
          readingCount,
          avgQuality,
          retryCount,
          validationErrors
        }
      }
    } catch (error) {
      console.error('❌ Pipeline failed:', error)
      throw error
    }
  }

  // ==========================================================================
  // STEP 1: INITIALIZE - SUBTOPIC SELECTION
  // ==========================================================================

  /**
   * Public helper for testing/planning specialized generation without invoking LLM
   */
  buildGenerationPlan(options: GenerationOptions = {}): GenerationPlan {
    const normalized: GenerationPlan['options'] = {
      mathCount: options.mathCount ?? 5,
      readingCount: options.readingCount ?? 5,
      specializedMode: options.specializedMode ?? false,
      moduleType: options.moduleType ?? 'both',
      difficulty: options.difficulty ?? 'mixed',
      includeImages: options.includeImages ?? true,
      includePassages: options.includePassages ?? true,
      storeInDatabase: options.storeInDatabase ?? true,
      temperature: options.temperature ?? 0.7,
      maxTokens: options.maxTokens ?? 16000,
      enableRetry: options.enableRetry ?? true,
      enableValidation: options.enableValidation ?? true,
      specificTopics: options.specificTopics,
      specificSubtopics: options.specificSubtopics
    }

    const { mathSubtopics, readingSubtopics } = this.selectSubtopics(normalized)

    return {
      options: normalized,
      mathSubtopics,
      readingSubtopics
    }
  }

  /**
   * Select random subtopics for generation
   */
  private selectSubtopics(options: GenerationOptions): {
    mathSubtopics: EnrichedSubtopic[]
    readingSubtopics: EnrichedSubtopic[]
  } {
    const allSubtopics = getAllSubtopics()
    const normalizedTopicFilters = (options.specificTopics || []).map(t => t.trim().toLowerCase())
    const normalizedSubtopicFilters = (options.specificSubtopics || []).map(s => s.trim().toLowerCase())

    const filteredByTopic = normalizedTopicFilters.length > 0
      ? allSubtopics.filter(s =>
        normalizedTopicFilters.includes(s.topicId.toLowerCase()) ||
        normalizedTopicFilters.includes(s.topicName.toLowerCase())
      )
      : allSubtopics

    const filteredSubtopics = normalizedSubtopicFilters.length > 0
      ? filteredByTopic.filter(s =>
        normalizedSubtopicFilters.includes(s.id.toLowerCase()) ||
        normalizedSubtopicFilters.includes(s.name.toLowerCase())
      )
      : filteredByTopic

    let mathSubtopics: EnrichedSubtopic[] = []
    let readingSubtopics: EnrichedSubtopic[] = []

    if (options.moduleType === 'math' || options.moduleType === 'both') {
      let mathPool = filteredSubtopics.filter(s => s.moduleType === 'math')
      if (options.specializedMode && mathPool.length > 0 && normalizedTopicFilters.length === 0 && normalizedSubtopicFilters.length === 0) {
        const uniqueTopics = [...new Set(mathPool.map(s => s.topicId))]
        const selectedTopicId = uniqueTopics[Math.floor(Math.random() * uniqueTopics.length)]
        mathPool = mathPool.filter(s => s.topicId === selectedTopicId)
      }
      mathSubtopics = this.selectRandomSubtopics(mathPool, options.mathCount || 5)
    }

    if (options.moduleType === 'reading-writing' || options.moduleType === 'both') {
      let readingPool = filteredSubtopics.filter(s => s.moduleType === 'reading-writing')
      if (options.specializedMode && readingPool.length > 0 && normalizedTopicFilters.length === 0 && normalizedSubtopicFilters.length === 0) {
        const uniqueTopics = [...new Set(readingPool.map(s => s.topicId))]
        const selectedTopicId = uniqueTopics[Math.floor(Math.random() * uniqueTopics.length)]
        readingPool = readingPool.filter(s => s.topicId === selectedTopicId)
      }
      readingSubtopics = this.selectRandomSubtopics(readingPool, options.readingCount || 5)
    }

    console.log(`Selected ${mathSubtopics.length} math subtopics, ${readingSubtopics.length} reading subtopics`)
    return { mathSubtopics, readingSubtopics }
  }

  /**
   * Select N random subtopics from pool (Fisher-Yates shuffle)
   */
  private selectRandomSubtopics(pool: EnrichedSubtopic[], count: number): EnrichedSubtopic[] {
    if (pool.length === 0 || count <= 0) {
      return []
    }

    const shuffled = [...pool]
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
    }

    if (count <= shuffled.length) {
      return shuffled.slice(0, count)
    }

    // When a user filters to a narrow topic/subtopic set, sample with replacement
    // so we can still generate the requested count.
    const selected = [...shuffled]
    while (selected.length < count) {
      selected.push(pool[Math.floor(Math.random() * pool.length)])
    }

    return selected
  }

  // ==========================================================================
  // STEP 2: GENERATE - LLM QUESTION CREATION
  // ==========================================================================

  /**
   * Generate math questions using LLM
   */
  private async generateMathQuestions(
    subtopics: EnrichedSubtopic[],
    options: GenerationOptions
  ): Promise<GeneratedQuestion[]> {
    if (subtopics.length === 0) return []

    console.log(`🧮 Generating ${subtopics.length} math questions...`)
    const prompt = buildMathQuestionsPrompt(
      subtopics as unknown as { name: string; topicName?: string; description?: string }[],
      {
        mathCount: subtopics.length,
        includeCharts: options.includeImages ?? true
      }
    )

    let response: string
    try {
      response = await this.callLLM(prompt, options)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      const isInvalidPrompt = /invalid_prompt|400 Bad Request/i.test(message)

      if (isInvalidPrompt && subtopics.length > 1) {
        const midpoint = Math.ceil(subtopics.length / 2)
        const left = await this.generateMathQuestions(subtopics.slice(0, midpoint), options)
        const right = await this.generateMathQuestions(subtopics.slice(midpoint), options)
        return [...left, ...right]
      }

      throw error
    }

    let questions = this.parseQuestions(response, subtopics, 'math')
    if (options.includeImages === false) {
      questions = questions.map(question => ({
        ...question,
        hasChart: false,
        chartDescription: undefined,
        graphType: undefined,
      }))
    }

    console.log(`✅ Parsed ${questions.length} math questions`)
    return questions
  }

  /**
   * Generate reading questions using LLM
   */
  private async generateReadingQuestions(
    subtopics: EnrichedSubtopic[],
    options: GenerationOptions
  ): Promise<GeneratedQuestion[]> {
    if (subtopics.length === 0) return []

    console.log(`📚 Generating ${subtopics.length} reading questions...`)
    const prompt = buildReadingQuestionsPrompt(
      subtopics as unknown as { name: string; topicName?: string; description?: string }[],
      {
        readingCount: subtopics.length,
        includePassages: options.includePassages ?? true
      }
    )

    const response = await this.callLLM(prompt, options)
    const questions = this.parseQuestions(response, subtopics, 'reading-writing')
    console.log(`✅ Parsed ${questions.length} reading questions`)
    return questions
  }

  /**
   * Call LLM API (Azure OpenAI)
   */
  private async callLLM(prompt: string, options: GenerationOptions): Promise<string> {
    const endpoint = this.getChatEndpoint()
    const apiKey = this.getApiKey()

    if (!endpoint || !apiKey) {
      throw new Error('Missing Azure OpenAI config: set AZURE_OPENAI_API_KEY and ENDPOINT_URL or AZURE_OPENAI_ENDPOINT')
    }

    console.log(`🌐 Calling LLM at ${endpoint.substring(0, 50)}...`)

    const requestBody: Record<string, unknown> = {
      messages: [
        {
          role: 'system',
          content: SYSTEM_ROLES.QUESTION_GENERATOR
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_completion_tokens: options.maxTokens || 16000  // Azure OpenAI requires max_completion_tokens for GPT-4o/newer models
    }

    const deploymentHint = (
      process.env.AZURE_OPENAI_DEPLOYMENT ||
      process.env.DEPLOYMENT_NAME ||
      endpoint
    ).toLowerCase()

    if (deploymentHint.includes('gpt-5')) {
      requestBody.reasoning_effort = 'minimal'
    }
    
    // Only add temperature if explicitly set and not default (some models only support default temperature=1)
    // if (options.temperature && options.temperature !== 1) {
    //   requestBody.temperature = options.temperature
    // }

    const timeoutMs = Number.parseInt(process.env.QUESTION_GENERATION_TIMEOUT_MS || '180000', 10)
    const controller = new AbortController()
    const timeoutHandle = setTimeout(() => controller.abort(), timeoutMs)

    let response: Response
    try {
      response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'api-key': apiKey,
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(requestBody),
        signal: controller.signal,
      })
    } catch (error) {
      if (error instanceof Error && error.name === 'AbortError') {
        throw new Error(`LLM request timed out after ${timeoutMs}ms`)
      }
      throw error
    } finally {
      clearTimeout(timeoutHandle)
    }

    if (!response.ok) {
      const errorText = await response.text()
      console.error(`❌ LLM API Error: ${response.status} ${response.statusText}`)
      console.error(errorText)
      throw new Error(`LLM API error: ${response.status} ${response.statusText}`)
    }

    const data = await response.json()

    const content = this.extractTextFromModelResponse(data)
    if (!content) {
      const responseKeys = data && typeof data === 'object' ? Object.keys(data).join(', ') : typeof data
      throw new Error(`Invalid LLM response structure (keys: ${responseKeys})`)
    }

    console.log(`✅ LLM response: ${content.length} characters`)
    return content
  }

  /**
   * Extract text from chat completions or responses-style payloads
   */
  private extractTextFromModelResponse(data: unknown): string | null {
    if (!data || typeof data !== 'object') return null
    const payload = data as Record<string, unknown>
    const choices = Array.isArray(payload.choices) ? payload.choices : []
    const firstChoice = choices[0]
    const firstChoiceObject = firstChoice && typeof firstChoice === 'object'
      ? (firstChoice as Record<string, unknown>)
      : null
    const message = firstChoiceObject?.message
    const messageObject = message && typeof message === 'object'
      ? (message as Record<string, unknown>)
      : null

    const messageContent = messageObject?.content
    if (typeof messageContent === 'string' && messageContent.trim()) {
      return messageContent
    }

    if (Array.isArray(messageContent)) {
      const combined = messageContent
        .map((item) => {
          if (typeof item === 'string') return item
          if (!item || typeof item !== 'object') return ''
          const obj = item as Record<string, unknown>
          const candidate = obj.text ?? obj.output_text ?? obj.content
          return typeof candidate === 'string' ? candidate : ''
        })
        .join('')
        .trim()
      if (combined) return combined
    }

    const completionText = firstChoiceObject?.text
    if (typeof completionText === 'string' && completionText.trim()) {
      return completionText
    }

    if (typeof payload.output_text === 'string' && payload.output_text.trim()) {
      return payload.output_text
    }

    if (Array.isArray(payload.output)) {
      const outputText = payload.output
        .flatMap((item) => {
          if (!item || typeof item !== 'object') return []
          const obj = item as Record<string, unknown>
          return Array.isArray(obj.content) ? obj.content : []
        })
        .map((item: unknown) => {
          if (typeof item === 'string') return item
          if (!item || typeof item !== 'object') return ''
          const obj = item as Record<string, unknown>
          const candidate = obj.text ?? obj.output_text ?? obj.content
          return typeof candidate === 'string' ? candidate : ''
        })
        .join('')
        .trim()
      if (outputText) return outputText
    }

    return null
  }

  /**
   * Parse LLM response into structured questions
   */
  private parseQuestions(
    response: string,
    subtopics: EnrichedSubtopic[],
    moduleType: 'math' | 'reading-writing'
  ): GeneratedQuestion[] {
    try {
      // Clean markdown code blocks
      let cleaned = response.trim()
      if (cleaned.startsWith('```json')) {
        cleaned = cleaned.slice(7)
      }
      if (cleaned.startsWith('```')) {
        cleaned = cleaned.slice(3)
      }
      if (cleaned.endsWith('```')) {
        cleaned = cleaned.slice(0, -3)
      }
      cleaned = cleaned.trim()

      const parsed = JSON.parse(cleaned)
      const questionsArray = Array.isArray(parsed) ? parsed : (parsed.questions || [])

      return questionsArray.map((q: Record<string, unknown>, index: number) => ({
        question: q.question || '',
        options: q.options || [],
        correctAnswer: typeof q.correctAnswer === 'number' ? q.correctAnswer : (typeof q.correct_answer === 'number' ? q.correct_answer : 0),
        explanation: q.explanation || '',
        subtopic: q.subtopic || subtopics[index]?.name || '',
        moduleType,
        hasChart: q.hasChart || q.has_chart || false,
        chartDescription: q.chartDescription || q.chart_description || '',
        graphType: q.graphType || q.graph_type || '',
        passage: q.passage || '',
        passageTitle: q.passageTitle || q.passage_title || '',
        passageAuthor: q.passageAuthor || q.passage_author || ''
      }))
    } catch (error) {
      console.error('❌ Failed to parse questions:', error)
      console.error('Response:', response.substring(0, 500))
      throw new Error('Failed to parse LLM response as JSON')
    }
  }

  // ==========================================================================
  // STEP 3: EVALUATE - GROK QUALITY SCORING
  // ==========================================================================

  /**
   * Evaluate all questions with Grok
   */
  private async evaluateQuestions(questions: GeneratedQuestion[]): Promise<EvaluatedQuestion[]> {
    console.log(`🔍 Evaluating ${questions.length} questions with Grok...`)

    const evaluated = await Promise.all(
      questions.map(q => this.evaluateQuestion(q))
    )

    const avgQuality = evaluated.reduce((sum, q) => sum + q.qualityScore, 0) / evaluated.length
    console.log(`✅ Evaluation complete: ${(avgQuality * 100).toFixed(1)}% average quality`)

    return evaluated
  }

  /**
   * Evaluate a single question with Grok (with fallback)
   */
  private async evaluateQuestion(question: GeneratedQuestion): Promise<EvaluatedQuestion> {
    try {
      const endpoint = this.getGrokEndpoint()
      const apiKey = this.getApiKey()

      if (!endpoint || !apiKey) {
        console.warn('⚠️  Grok endpoint not configured, using fallback evaluation')
        return this.fallbackEvaluation(question)
      }

      const evaluationPrompt = `Evaluate this SAT question and return ONLY one-line JSON.
Question: ${question.question}
Options: ${question.options.join(' | ')}
CorrectAnswerIndex: ${question.correctAnswer}
Explanation: ${question.explanation}
Required JSON keys: difficulty, qualityScore, isAccepted, evaluationFeedback`

      const firstAttempt = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'api-key': apiKey,
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          messages: [
            {
              role: 'system',
              content: `${SYSTEM_ROLES.EVALUATOR}\nReturn compact JSON only. No markdown, no prose.`
            },
            {
              role: 'user',
              content: evaluationPrompt
            }
          ],
          reasoning_effort: 'minimal',
          response_format: { type: 'json_object' },
          max_completion_tokens: 500
        })
      })

      if (!firstAttempt.ok) {
        const errorText = await firstAttempt.text()
        console.warn(`⚠️  Grok evaluation failed (${firstAttempt.status}): ${errorText.substring(0, 200)}`)
        return this.fallbackEvaluation(question)
      }

      const firstData = await firstAttempt.json()
      let content = this.extractTextFromModelResponse(firstData)

      if (!content && firstData?.choices?.[0]?.finish_reason === 'length') {
        console.warn('⚠️  Grok response hit token limit with empty content, retrying with shorter prompt...')

        const retryResponse = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'api-key': apiKey,
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            messages: [
              {
                role: 'system',
                content: 'Return only minified JSON with keys difficulty,qualityScore,isAccepted,evaluationFeedback.'
              },
              {
                role: 'user',
                content: `Evaluate SAT quality 0-100. q=${question.question.slice(0, 700)} opts=${question.options.join(' | ').slice(0, 500)} ans=${question.correctAnswer} exp=${question.explanation.slice(0, 800)}`
              }
            ],
            reasoning_effort: 'minimal',
            response_format: { type: 'json_object' },
            max_completion_tokens: 250
          })
        })

        if (retryResponse.ok) {
          const retryData = await retryResponse.json()
          content = this.extractTextFromModelResponse(retryData)
        }
      }

      if (!content) {
        console.warn(`⚠️  Grok response missing content. Response structure:`, JSON.stringify(firstData).substring(0, 200))
        return this.fallbackEvaluation(question)
      }

      console.log(`📊 Grok evaluation response (first 200 chars): ${content.substring(0, 200)}`)
      const evaluation = this.parseEvaluation(content)

      return {
        ...question,
        difficulty: evaluation.difficulty,
        qualityScore: evaluation.qualityScore / 100, // Normalize to 0-1
        isAccepted: evaluation.isAccepted,
        evaluationFeedback: evaluation.evaluationFeedback
      }
    } catch (error) {
      console.warn('⚠️  Grok evaluation error:', error)
      return this.fallbackEvaluation(question)
    }
  }

  /**
   * Parse Grok evaluation response
   */
  private parseEvaluation(response: string): {
    difficulty: 'easy' | 'medium' | 'hard'
    qualityScore: number
    isAccepted: boolean
    evaluationFeedback: string
  } {
    try {
      let cleaned = response.trim()
      if (cleaned.startsWith('```json')) cleaned = cleaned.slice(7)
      if (cleaned.startsWith('```')) cleaned = cleaned.slice(3)
      if (cleaned.endsWith('```')) cleaned = cleaned.slice(0, -3)
      cleaned = cleaned.trim()

      const parsed = JSON.parse(cleaned)

      const normalizedDifficulty = (() => {
        const raw = String(parsed.difficulty || 'medium').toLowerCase()
        if (raw.includes('easy')) return 'easy'
        if (raw.includes('hard')) return 'hard'
        return 'medium'
      })()

      const normalizedQualityScore = (() => {
        const raw = Number(parsed.qualityScore)
        if (!Number.isFinite(raw)) return 75

        // Some evaluators return 0-1, others 0-100. Normalize to 0-100.
        const asPercentage = raw <= 1 ? raw * 100 : raw
        return Math.max(0, Math.min(100, asPercentage))
      })()

      return {
        difficulty: normalizedDifficulty,
        qualityScore: normalizedQualityScore,
        isAccepted: parsed.isAccepted !== false,
        evaluationFeedback: parsed.evaluationFeedback || 'Evaluated by Grok'
      }
    } catch {
      console.warn('⚠️  Failed to parse evaluation, using defaults')
      return {
        difficulty: 'medium',
        qualityScore: 75,
        isAccepted: true,
        evaluationFeedback: 'Evaluation parse failed'
      }
    }
  }

  /**
   * Fallback evaluation when Grok is unavailable
   */
  private fallbackEvaluation(question: GeneratedQuestion): EvaluatedQuestion {
    console.log('📋 Using fallback evaluation')

    const optionsCount = Array.isArray(question.options) ? question.options.length : 0
    const hasValidAnswerIndex = question.correctAnswer >= 0 && question.correctAnswer < optionsCount
    const questionLengthOk = (question.question || '').trim().length >= 30
    const explanationLengthOk = (question.explanation || '').trim().length >= 40
    const hasPassageIfReading = this.getReadingPassageIssues(question).length === 0

    const structuralScoreParts = [
      optionsCount === 4,
      hasValidAnswerIndex,
      questionLengthOk,
      explanationLengthOk,
      hasPassageIfReading
    ]

    const passedParts = structuralScoreParts.filter(Boolean).length
    const qualityScore = 0.55 + (passedParts / structuralScoreParts.length) * 0.3

    return {
      ...question,
      difficulty: 'medium',
      qualityScore,
      isAccepted: qualityScore >= QUALITY_THRESHOLDS.MIN_ACCEPTABLE_QUALITY,
      evaluationFeedback: `Fallback evaluation - structural heuristic (${Math.round(qualityScore * 100)}%)`
    }
  }

  private normalizeSubtopicKey(value: string): string {
    return value
      .toLowerCase()
      .replace(/&/g, 'and')
      .replace(/[^a-z0-9]+/g, ' ')
      .trim()
      .replace(/\s+/g, ' ')
  }

  private countWords(text: string): number {
    return text
      .trim()
      .split(/\s+/)
      .filter(Boolean)
      .length
  }

  private requiresFullLengthReadingPassage(subtopic: string | null | undefined): boolean {
    const key = this.normalizeSubtopicKey(subtopic || '')
    return FULL_PASSAGE_SUBTOPICS.has(key)
  }

  private getReadingPassageIssues(question: Pick<GeneratedQuestion, 'moduleType' | 'passage' | 'subtopic'>): string[] {
    if (question.moduleType !== 'reading-writing') {
      return []
    }

    const passage = (question.passage || '').trim()
    if (!passage) {
      return ['missing reading passage']
    }

    const issues: string[] = []
    const wordCount = this.countWords(passage)

    if (READING_PASSAGE_OMISSION_MARKER.test(passage)) {
      issues.push('passage contains omission markers such as "..." or "…"')
    }

    if (this.requiresFullLengthReadingPassage(question.subtopic) && wordCount < PASSAGE_LIMITS.MIN_WORDS) {
      issues.push(`passage is too short for a full reading passage (${wordCount} words, need at least ${PASSAGE_LIMITS.MIN_WORDS})`)
    }

    return issues
  }

  private applyReadingPassageGuardrails(questions: EvaluatedQuestion[]): EvaluatedQuestion[] {
    let rejectedCount = 0

    const guardedQuestions = questions.map(question => {
      const issues = this.getReadingPassageIssues(question)
      if (issues.length === 0) {
        return question
      }

      rejectedCount += 1

      return {
        ...question,
        qualityScore: Math.min(question.qualityScore, 0.4),
        isAccepted: false,
        evaluationFeedback: `${question.evaluationFeedback} | Passage integrity failure: ${issues.join('; ')}`
      }
    })

    if (rejectedCount > 0) {
      console.warn(`⚠️  Rejected ${rejectedCount} reading question(s) due to incomplete or abbreviated passages`)
    }

    return guardedQuestions
  }

  private mapTopicToDrillCategory(
    topicName: string | null | undefined,
    moduleType: 'math' | 'reading-writing'
  ): string | null {
    if (!topicName) return null

    const topicKey = this.normalizeSubtopicKey(topicName)

    if (moduleType === 'reading-writing') {
      if (topicKey.includes('reading comprehension') || topicKey === 'reading comprehension') {
        return 'reading-comprehension'
      }
      if (topicKey.includes('writing and language')) {
        return 'writing-language'
      }
      if (topicKey.includes('grammar')) {
        return 'grammar'
      }
      if (topicKey.includes('vocabulary')) {
        return 'vocabulary'
      }
      return null
    }

    if (topicKey.includes('algebra')) return 'algebra'
    if (topicKey.includes('advanced math')) return 'advanced-math'
    if (topicKey.includes('geometry') || topicKey.includes('trigonometry')) return 'geometry'
    if (topicKey.includes('statistics') || topicKey.includes('probability') || topicKey.includes('data analysis')) {
      return 'problem-solving-data-analysis'
    }

    return null
  }

  private deriveDrillCategory(
    moduleType: 'math' | 'reading-writing',
    topicName: string | null | undefined,
    subtopicName: string | null | undefined
  ): string {
    const subtopicKey = this.normalizeSubtopicKey(subtopicName || '')

    if (moduleType === 'reading-writing') {
      if (subtopicKey.includes('vocabulary')) {
        return 'vocabulary'
      }

      if (subtopicKey.includes('grammar') || subtopicKey.includes('punctuation')) {
        return 'grammar'
      }

      if (
        subtopicKey.includes('rhetorical') ||
        subtopicKey.includes('transition') ||
        subtopicKey.includes('sentence structure') ||
        subtopicKey.includes('style')
      ) {
        return 'writing-language'
      }

      const mappedTopic = this.mapTopicToDrillCategory(topicName, moduleType)
      if (mappedTopic) {
        return mappedTopic
      }

      return 'reading-comprehension'
    }

    const mappedTopic = this.mapTopicToDrillCategory(topicName, moduleType)
    if (mappedTopic) {
      return mappedTopic
    }

    if (
      subtopicKey.includes('statistics') ||
      subtopicKey.includes('probability') ||
      subtopicKey.includes('data analysis')
    ) {
      return 'problem-solving-data-analysis'
    }

    if (
      subtopicKey.includes('geometry') ||
      subtopicKey.includes('trigonometry') ||
      subtopicKey.includes('triangle') ||
      subtopicKey.includes('circle')
    ) {
      return 'geometry'
    }

    if (
      subtopicKey.includes('quadratic') ||
      subtopicKey.includes('polynomial') ||
      subtopicKey.includes('exponential') ||
      subtopicKey.includes('logarithmic') ||
      subtopicKey.includes('complex number') ||
      subtopicKey.includes('sequence') ||
      subtopicKey.includes('series') ||
      subtopicKey.includes('rational expression')
    ) {
      return 'advanced-math'
    }

    return 'algebra'
  }

  // ==========================================================================
  // STEP 4: RETRY - REGENERATE LOW-QUALITY QUESTIONS (from Migration)
  // ==========================================================================

  /**
   * Retry low-quality questions (≤80% threshold)
   * Up to 5 regeneration attempts per question
   */
  private async retryLowQualityQuestions(
    questions: EvaluatedQuestion[],
    options: GenerationOptions
  ): Promise<{ questions: EvaluatedQuestion[]; retryCount: number }> {
    let retryCount = 0
    const threshold = QUALITY_THRESHOLDS.REGENERATION_THRESHOLD
    const maxAttempts = QUALITY_THRESHOLDS.MAX_REGENERATION_ATTEMPTS

    const retriedQuestions = await Promise.all(
      questions.map(async (question) => {
        if (question.qualityScore > threshold) {
          return question // Already acceptable
        }

        console.log(`🔄 Retrying low-quality question (${(question.qualityScore * 100).toFixed(0)}% ≤ ${(threshold * 100).toFixed(0)}%)`)
        
        let currentQuestion = question
        let attempts = 0
        const previousScores: number[] = []

        while (attempts < maxAttempts && currentQuestion.qualityScore <= threshold) {
          attempts++
          retryCount++

          try {
            // Regenerate the question
            const regenerated = await this.regenerateSingleQuestion(currentQuestion, options)
            
            // Re-evaluate
            const evaluated = await this.evaluateQuestion(regenerated)
            
            console.log(`  Attempt ${attempts}: Quality = ${(evaluated.qualityScore * 100).toFixed(0)}%`)

            // Check for plateau detection - if last 3 scores are identical, stop retrying
            previousScores.push(evaluated.qualityScore)
            if (previousScores.length >= 3) {
              const lastThree = previousScores.slice(-3)
              const allSame = lastThree.every(score => Math.abs(score - lastThree[0]) < 0.01) // Within 1%
              if (allSame) {
                console.log(`  ⏹️  Quality plateau detected (${(lastThree[0] * 100).toFixed(0)}% × 3), stopping retries`)
                return {
                  ...evaluated,
                  evaluationFeedback: `${evaluated.evaluationFeedback} (Quality plateau reached)`
                }
              }
            }

            if (evaluated.qualityScore > threshold) {
              console.log(`  ✅ Quality improved, accepting`)
              return evaluated
            }

            currentQuestion = evaluated
          } catch (error) {
            console.error(`  ❌ Retry attempt ${attempts} failed:`, error)
            break
          }
        }

        console.log(`  ⚠️  Max retries reached (${attempts}), accepting last attempt`)
        return {
          ...currentQuestion,
          evaluationFeedback: `${currentQuestion.evaluationFeedback} (Accepted after ${attempts} retries)`
        }
      })
    )

    console.log(`🔄 Retry summary: ${retryCount} total regeneration attempts`)
    return { questions: retriedQuestions, retryCount }
  }

  /**
   * Regenerate a single question using same parameters
   */
  private async regenerateSingleQuestion(
    question: EvaluatedQuestion,
    options: GenerationOptions
  ): Promise<GeneratedQuestion> {
    console.log(`  🔄 Regenerating ${question.moduleType} question for ${question.subtopic}`)

    const allSubtopics = getAllSubtopics()
    
    // Try exact match first
    let subtopic = allSubtopics.find(
      s => s.name.toLowerCase() === question.subtopic.toLowerCase() && s.moduleType === question.moduleType
    )
    
    // If no exact match, try matching without parentheses (e.g., "Main Ideas (Reading)" → "Main Ideas")
    if (!subtopic) {
      const cleanedQuestionSubtopic = question.subtopic.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase()
      subtopic = allSubtopics.find(
        s => s.name.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase() === cleanedQuestionSubtopic && 
             s.moduleType === question.moduleType
      )
    }
    
    // If still no match, try partial match (contains)
    if (!subtopic) {
      const cleanedQuestionSubtopic = question.subtopic.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase()
      subtopic = allSubtopics.find(
        s => (s.name.toLowerCase().includes(cleanedQuestionSubtopic) || 
              cleanedQuestionSubtopic.includes(s.name.toLowerCase())) &&
             s.moduleType === question.moduleType
      )
    }

    if (!subtopic) {
      console.warn(`⚠️  Subtopic not found: "${question.subtopic}" - using fallback`)
      // Return original question if we can't find subtopic (better than crashing)
      return question
    }

    if (question.moduleType === 'math') {
      const questions = await this.generateMathQuestions([subtopic], options)
      return questions[0] || question
    } else {
      const questions = await this.generateReadingQuestions([subtopic], options)
      return questions[0] || question
    }
  }

  // ==========================================================================
  // STEP 5: VALIDATE - DIAGRAM CONSISTENCY CHECK (from Migration)
  // ==========================================================================

  /**
   * Validate diagram consistency: -40% penalty for questions mentioning diagrams without images
   */
  private async validateDiagramConsistency(questions: EvaluatedQuestion[]): Promise<EvaluatedQuestion[]> {
    console.log('🔍 Validating diagram consistency...')

    return questions.map(question => {
      // Only validate math questions
      if (question.moduleType !== 'math') {
        return question
      }

      const questionLower = question.question.toLowerCase()
      
      // More precise detection: look for phrases that indicate visual elements
      const diagramPhrases = [
        'in the diagram',
        'in the chart',
        'in the graph',
        'in the figure',
        'the diagram',
        'the chart',
        'the graph',
        'the figure',
        'coordinate plane',
        'shown in',
        'shown below',
        'shown above',
        'as shown',
        'illustrated in',
        'displayed in',
        'refers to the',
        'look at the'
      ]
      
      const mentionsDiagram = diagramPhrases.some(phrase => questionLower.includes(phrase))
      
      const hasImageUrl = !!question.imageUrl && question.imageUrl.length > 0
      const hasChartDescription = !!question.chartDescription && question.chartDescription.length > 10

      // CRITICAL ERROR: Question mentions diagram but has no image
      if (mentionsDiagram && !hasImageUrl) {
        console.log(`  ⚠️  CRITICAL: Question mentions diagram without image`)
        console.log(`     Question: "${question.question.substring(0, 60)}..."`)
        console.log(`     hasChart: ${question.hasChart}, imageUrl: ${hasImageUrl}, chartDesc: ${hasChartDescription}`)

        const newQualityScore = Math.max(0.3, question.qualityScore - 0.4) // -40% penalty

        return {
          ...question,
          qualityScore: newQualityScore,
          isAccepted: false,
          evaluationFeedback: `${question.evaluationFeedback} | CRITICAL ERROR: Question references diagram/chart that doesn't exist. Quality penalized from ${(question.qualityScore * 100).toFixed(0)}% to ${(newQualityScore * 100).toFixed(0)}%.`
        }
      }

      // ERROR: Has chart flag but no image generated
      if (question.hasChart && !hasImageUrl) {
        console.log(`  ⚠️  ERROR: Chart generation failed`)
        console.log(`     Question: "${question.question.substring(0, 60)}..."`)

        const newQualityScore = Math.max(0.4, question.qualityScore - 0.25) // -25% penalty

        return {
          ...question,
          qualityScore: newQualityScore,
          isAccepted: false,
          evaluationFeedback: `${question.evaluationFeedback} | ERROR: Chart/diagram generation failed. Quality penalized from ${(question.qualityScore * 100).toFixed(0)}% to ${(newQualityScore * 100).toFixed(0)}%.`
        }
      }

      // SUCCESS: Diagram mentioned and image exists
      if (mentionsDiagram && hasImageUrl) {
        console.log(`  ✅ Diagram consistency OK: "${question.question.substring(0, 60)}..."`)
      }

      return question
    })
  }

  // ==========================================================================
  // STEP 6: STORE - DATABASE PERSISTENCE WITH IMAGES
  // ==========================================================================

  /**
   * Store questions in database (with image generation)
   */
  private async storeQuestions(questions: EvaluatedQuestion[]): Promise<void> {
    console.log(`💾 Storing ${questions.length} questions in database...`)

    // First, generate images for questions that need them
    const questionsWithImages = await this.generateAndStoreImages(questions)

    const dbSubtopics = await this.prisma.subtopic.findMany({
      select: {
        id: true,
        name: true,
        topic: {
          select: {
            name: true
          }
        }
      }
    })

    const dbTopics = await this.prisma.topic.findMany({
      where: { isActive: true },
      select: {
        id: true,
        name: true,
        moduleType: true
      }
    })

    const subtopicMap = new Map(
      dbSubtopics.map((subtopic) => [this.normalizeSubtopicKey(subtopic.name), subtopic])
    )

    // Then store in database
    for (const question of questionsWithImages) {
      try {
        const questionSubtopicKey = this.normalizeSubtopicKey(question.subtopic)

        let matchedSubtopic = subtopicMap.get(questionSubtopicKey)

        if (!matchedSubtopic) {
          matchedSubtopic = dbSubtopics.find((subtopic) => {
            const dbKey = this.normalizeSubtopicKey(subtopic.name)
            return dbKey.includes(questionSubtopicKey) || questionSubtopicKey.includes(dbKey)
          })
        }

        if (!matchedSubtopic) {
          const normalizedSubtopic = this.normalizeSubtopicKey(question.subtopic || '')
          const moduleTopics = dbTopics.filter(topic => topic.moduleType === question.moduleType)

          const matchedTopic = moduleTopics.find(topic => this.normalizeSubtopicKey(topic.name) === normalizedSubtopic)
            || moduleTopics.find(topic => {
              const topicKey = this.normalizeSubtopicKey(topic.name)
              return topicKey.includes(normalizedSubtopic) || normalizedSubtopic.includes(topicKey)
            })
            || moduleTopics[0]

          if (matchedTopic) {
            const created = await this.prisma.subtopic.create({
              data: {
                topicId: matchedTopic.id,
                name: question.subtopic,
                description: `Auto-created from unified generator (${question.moduleType})`,
                targetQuestions: 100,
                currentCount: 0,
                isActive: true
              },
              select: {
                id: true,
                name: true,
                topic: {
                  select: {
                    name: true
                  }
                }
              }
            })

            matchedSubtopic = created
            subtopicMap.set(questionSubtopicKey, created)
            console.log(`  🆕 Created missing subtopic in DB: ${question.subtopic} (topic: ${matchedTopic.name})`)
          } else {
            console.warn(`  ⚠️  Subtopic not found in DB and no topic available: ${question.subtopic}, storing with null subtopicId`)
          }
        }

        const derivedCategory = this.deriveDrillCategory(
          question.moduleType,
          matchedSubtopic?.topic.name,
          matchedSubtopic?.name || question.subtopic
        )

        await this.prisma.question.create({
          data: {
            question: question.question,
            options: JSON.stringify(question.options),
            correctAnswer: question.correctAnswer,
            explanation: question.explanation,
            moduleType: question.moduleType,
            difficulty: question.difficulty,
            subtopicId: matchedSubtopic?.id || null,
            category: derivedCategory,
            subtopic: question.subtopic,
            chartData: question.hasChart ? JSON.stringify({
              description: question.chartDescription,
              graphType: question.graphType,
              hasChart: true
            }) : null,
            imageUrl: question.imageUrl || null,
            imageAlt: question.imageAlt || null,
            passage: question.passage || null,
            reviewStatus: question.isAccepted ? 'approved' : 'pending',
            reviewComments: `Quality score: ${(question.qualityScore * 100).toFixed(1)}%`,
            timeEstimate: 90, // Default 90 seconds
            source: 'AI Generated (Unified Service)',
            tags: JSON.stringify([question.moduleType, question.difficulty, question.subtopic]),
            isActive: true
          }
        })

        console.log(`  ✅ Stored: ${question.subtopic} (${(question.qualityScore * 100).toFixed(0)}% quality)`)
      } catch (error) {
        console.error(`  ❌ Failed to store question:`, error)
      }
    }

    console.log(`✅ Database storage complete`)
  }

  /**
   * Generate and store images for questions with chart descriptions
   */
  private async generateAndStoreImages(questions: EvaluatedQuestion[]): Promise<EvaluatedQuestion[]> {
    const questionsWithCharts = questions.filter(
      q => q.hasChart && q.chartDescription && q.moduleType === 'math'
    )

    console.log(`🎨 Generating images for ${questionsWithCharts.length} questions with charts...`)

    if (questionsWithCharts.length === 0) {
      return questions
    }

    // Dynamically import image service
    const { imageGenerationService } = await import('./imageGenerationService')

    const questionsWithImages = await Promise.all(
      questions.map(async (question) => {
        if (question.hasChart && question.chartDescription && question.moduleType === 'math') {
          try {
            console.log(`  🎨 Generating image for: "${question.question.substring(0, 50)}..."`)

            const chartConfig = {
              type: (question.graphType as 'coordinate-plane' | 'bar-chart' | 'scatter-plot' | 'box-plot' | 'geometric-diagram' | 'function-graph') || 'coordinate-plane',
              description: question.chartDescription,
              width: 600,
              height: 400
            }

            // Try DALL-E first
            let imageUrl = await imageGenerationService.generateChartImage(chartConfig)

            // Fallback to SVG if DALL-E fails
            if (!imageUrl) {
              console.log('    📋 DALL-E failed, generating SVG fallback...')
              imageUrl = await imageGenerationService.generateSVGChart(chartConfig)
            }

            if (imageUrl) {
              console.log(`    ✅ Image generated: ${imageUrl.substring(0, 80)}...`)
              return {
                ...question,
                imageUrl,
                imageAlt: question.chartDescription
              }
            } else {
              console.error(`    ❌ Image generation failed`)
              return question
            }
          } catch (error) {
            console.error('    ❌ Image generation error:', error)
            return question
          }
        }

        return question
      })
    )

    const successCount = questionsWithImages.filter(q => q.imageUrl).length
    console.log(`✅ Image generation complete: ${successCount}/${questionsWithCharts.length} successful`)

    return questionsWithImages
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export const unifiedQuestionGenerator = new UnifiedQuestionGenerator()
