/**
 * Unified Question Generator Service
 * 
 * This service consolidates all question generation logic into a single, production-ready service.
 * It combines the clean architecture of CLEAN's implementation with the production features
 * from Migration's aiQuestionService.
 * 
 * Key Features:
 * - 6-step pipeline: Initialize → Generate → Evaluate → Retry → Validate → Store
 * - Quality retry logic: Up to 5 retries for questions below 80% quality threshold
 * - Diagram consistency validation: -40% penalty for missing diagrams
 * - Dynamic endpoint configuration: Supports multiple Azure OpenAI endpoints
 * - Comprehensive error handling and logging
 * 
 * Architecture: Based on ADR-47 and SPEC-47
 * Epic: #46, Feature: #47, Story: #51
 */

import { PrismaClient } from '@prisma/client'
import { getAllSubtopics, type SATSubtopic } from '@/data/sat-topics'
import { buildMathQuestionsPrompt, buildReadingQuestionsPrompt } from './questionPromptTemplates'
import { SYSTEM_ROLES } from './promptConfig'

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

// Enriched subtopic type returned by getAllSubtopics()
type EnrichedSubtopic = SATSubtopic & { topicId: string; topicName: string; moduleType: 'reading-writing' | 'math' }

/**
 * Quality thresholds for question acceptance and regeneration
 */
const QUALITY_THRESHOLDS = {
  REGENERATION_THRESHOLD: 0.80, // Regenerate if quality ≤80%
  MAX_REGENERATION_ATTEMPTS: 5,  // Max 5 retries per question
  MIN_ACCEPTABLE_QUALITY: 0.70   // Absolute minimum to store
} as const

/**
 * Raw question generated by LLM (before evaluation)
 */
export interface GeneratedQuestion {
  question: string
  options: string[]
  correctAnswer: number // Index of correct answer (0-based)
  explanation: string
  subtopic: string
  moduleType: 'math' | 'reading-writing'
  hasChart: boolean
  chartDescription?: string
  graphType?: string
  passage?: string
  passageTitle?: string
  passageAuthor?: string
}

/**
 * Question after Grok evaluation (adds quality metrics)
 */
export interface EvaluatedQuestion extends GeneratedQuestion {
  difficulty: 'easy' | 'medium' | 'hard'
  qualityScore: number
  isAccepted: boolean
  evaluationFeedback: string
  imageUrl?: string
  imageAlt?: string
}

/**
 * Options for question generation
 */
export interface GenerationOptions {
  mathCount?: number
  readingCount?: number
  specificTopics?: string[]
  specificSubtopics?: string[]
  moduleType?: 'math' | 'reading-writing' | 'both'
  difficulty?: 'easy' | 'medium' | 'hard' | 'mixed'
  includeImages?: boolean
  includePassages?: boolean
  storeInDatabase?: boolean
  temperature?: number
  maxTokens?: number
  enableRetry?: boolean
  enableValidation?: boolean
}

/**
 * Result returned by generateQuestions()
 */
export interface GenerationResult {
  questions: EvaluatedQuestion[]
  summary: {
    total: number
    accepted: number
    rejected: number
    mathCount: number
    readingCount: number
    avgQuality: number
    retryCount: number
    validationErrors: number
  }
}

// ============================================================================
// UNIFIED QUESTION GENERATOR CLASS
// ============================================================================

export class UnifiedQuestionGenerator {
  private prisma: PrismaClient

  constructor() {
    this.prisma = new PrismaClient()
  }

  // ==========================================================================
  // CONFIGURATION METHODS (from Migration)
  // ==========================================================================

  /**
   * Get Azure OpenAI API key from environment
   */
  private getApiKey(): string {
    return process.env.AZURE_OPENAI_API_KEY || ''
  }

  /**
   * Get chat completion endpoint URL (supports multiple configuration patterns)
   */
  private getChatEndpoint(): string {
    const directUrl = process.env.ENDPOINT_URL
    if (directUrl) return directUrl

    const base = process.env.AZURE_OPENAI_ENDPOINT
    const deployment = process.env.AZURE_OPENAI_DEPLOYMENT || process.env.DEPLOYMENT_NAME || 'gpt-4o'
    const apiVersion = process.env.AZURE_OPENAI_API_VERSION || process.env.API_VERSION || '2025-01-01-preview'

    if (!base) return ''
    return `${base.replace(/\/$/, '')}/openai/deployments/${deployment}/chat/completions?api-version=${apiVersion}`
  }

  /**
   * Get Grok evaluation endpoint (falls back to chat endpoint if not configured)
   */
  private getGrokEndpoint(): string {
    return process.env.GROK_ENDPOINT || this.getChatEndpoint()
  }

  // ==========================================================================
  // MAIN ENTRY POINT: 6-STEP PIPELINE
  // ==========================================================================

  /**
   * Generate SAT questions using the 6-step pipeline:
   * 1. Initialize - Select subtopics and validate configuration
   * 2. Generate - Create raw questions via LLM
   * 3. Evaluate - Score questions with Grok
   * 4. Retry - Regenerate low-quality questions (≤80%)
   * 5. Validate - Check diagram consistency
   * 6. Store - Save to database with images
   * 
   * @param options - Generation configuration
   * @returns Generation result with questions and summary
   */
  async generateQuestions(options: GenerationOptions = {}): Promise<GenerationResult> {
    const startTime = Date.now()
    console.log('🚀 Starting 6-step question generation pipeline...')
    console.log('Options:', JSON.stringify(options, null, 2))

    const defaults: GenerationOptions = {
      mathCount: 5,
      readingCount: 5,
      moduleType: 'both',
      difficulty: 'mixed',
      includeImages: true,
      includePassages: true,
      storeInDatabase: true,
      temperature: 0.7,
      maxTokens: 16000,
      enableRetry: true,
      enableValidation: true,
      ...options
    }

    try {
      // Step 1: Initialize - Select subtopics
      console.log('\n📋 Step 1/6: Initialize - Selecting subtopics...')
      const { mathSubtopics, readingSubtopics } = this.selectSubtopics(defaults)

      // Step 2: Generate - Create raw questions
      console.log('\n🤖 Step 2/6: Generate - Creating questions with LLM...')
      const mathQuestions = defaults.mathCount! > 0 
        ? await this.generateMathQuestions(mathSubtopics, defaults) 
        : []
      const readingQuestions = defaults.readingCount! > 0 
        ? await this.generateReadingQuestions(readingSubtopics, defaults) 
        : []
      const rawQuestions = [...mathQuestions, ...readingQuestions]
      console.log(`✅ Generated ${rawQuestions.length} raw questions (${mathQuestions.length} math, ${readingQuestions.length} reading)`)

      // Step 3: Evaluate - Score with Grok
      console.log('\n🔍 Step 3/6: Evaluate - Scoring questions with Grok...')
      const evaluatedQuestions = await this.evaluateQuestions(rawQuestions)
      console.log(`✅ Evaluated ${evaluatedQuestions.length} questions`)

      // Step 4: Retry - Regenerate low-quality questions
      let retriedQuestions = evaluatedQuestions
      let retryCount = 0
      if (defaults.enableRetry) {
        console.log('\n🔄 Step 4/6: Retry - Regenerating low-quality questions...')
        const retryResult = await this.retryLowQualityQuestions(evaluatedQuestions, defaults)
        retriedQuestions = retryResult.questions
        retryCount = retryResult.retryCount
        console.log(`✅ Retry complete: ${retryCount} questions regenerated`)
      } else {
        console.log('\n⏭️  Step 4/6: Retry - Skipped (enableRetry=false)')
      }

      // Step 5: Validate - Check diagram consistency
      let validatedQuestions = retriedQuestions
      let validationErrors = 0
      if (defaults.enableValidation) {
        console.log('\n✅ Step 5/6: Validate - Checking diagram consistency...')
        validatedQuestions = await this.validateDiagramConsistency(retriedQuestions)
        validationErrors = validatedQuestions.filter(q => q.evaluationFeedback.includes('CRITICAL ERROR')).length
        console.log(`✅ Validation complete: ${validationErrors} errors found`)
      } else {
        console.log('\n⏭️  Step 5/6: Validate - Skipped (enableValidation=false)')
      }

      // Step 6: Store - Save to database
      if (defaults.storeInDatabase) {
        console.log('\n💾 Step 6/6: Store - Saving to database...')
        const questionsToStore = validatedQuestions.filter(q => q.isAccepted)
        await this.storeQuestions(questionsToStore)
        console.log(`✅ Stored ${questionsToStore.length} accepted questions`)
      } else {
        console.log('\n⏭️  Step 6/6: Store - Skipped (storeInDatabase=false)')
      }

      // Generate summary
      const accepted = validatedQuestions.filter(q => q.isAccepted)
      const rejected = validatedQuestions.filter(q => !q.isAccepted)
      const mathCount = validatedQuestions.filter(q => q.moduleType === 'math').length
      const readingCount = validatedQuestions.filter(q => q.moduleType === 'reading-writing').length
      const avgQuality = validatedQuestions.reduce((sum, q) => sum + q.qualityScore, 0) / validatedQuestions.length

      const duration = ((Date.now() - startTime) / 1000).toFixed(2)
      console.log(`\n🎉 Pipeline complete in ${duration}s`)
      console.log(`📊 Summary: ${accepted.length}/${validatedQuestions.length} accepted (${(avgQuality * 100).toFixed(1)}% avg quality)`)

      return {
        questions: validatedQuestions,
        summary: {
          total: validatedQuestions.length,
          accepted: accepted.length,
          rejected: rejected.length,
          mathCount,
          readingCount,
          avgQuality,
          retryCount,
          validationErrors
        }
      }
    } catch (error) {
      console.error('❌ Pipeline failed:', error)
      throw error
    }
  }

  // ==========================================================================
  // STEP 1: INITIALIZE - SUBTOPIC SELECTION
  // ==========================================================================

  /**
   * Select random subtopics for generation
   */
  private selectSubtopics(options: GenerationOptions): {
    mathSubtopics: EnrichedSubtopic[]
    readingSubtopics: EnrichedSubtopic[]
  } {
    const allSubtopics = getAllSubtopics()

    let mathSubtopics: EnrichedSubtopic[] = []
    let readingSubtopics: EnrichedSubtopic[] = []

    if (options.moduleType === 'math' || options.moduleType === 'both') {
      const mathPool = allSubtopics.filter(s => s.moduleType === 'math')
      mathSubtopics = this.selectRandomSubtopics(mathPool, options.mathCount || 5)
    }

    if (options.moduleType === 'reading-writing' || options.moduleType === 'both') {
      const readingPool = allSubtopics.filter(s => s.moduleType === 'reading-writing')
      readingSubtopics = this.selectRandomSubtopics(readingPool, options.readingCount || 5)
    }

    console.log(`Selected ${mathSubtopics.length} math subtopics, ${readingSubtopics.length} reading subtopics`)
    return { mathSubtopics, readingSubtopics }
  }

  /**
   * Select N random subtopics from pool (Fisher-Yates shuffle)
   */
  private selectRandomSubtopics(pool: EnrichedSubtopic[], count: number): EnrichedSubtopic[] {
    const shuffled = [...pool]
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
    }
    return shuffled.slice(0, Math.min(count, shuffled.length))
  }

  // ==========================================================================
  // STEP 2: GENERATE - LLM QUESTION CREATION
  // ==========================================================================

  /**
   * Generate math questions using LLM
   */
  private async generateMathQuestions(
    subtopics: EnrichedSubtopic[],
    options: GenerationOptions
  ): Promise<GeneratedQuestion[]> {
    if (subtopics.length === 0) return []

    console.log(`🧮 Generating ${subtopics.length} math questions...`)
    const prompt = buildMathQuestionsPrompt(
      subtopics as unknown as { name: string; topicName?: string; description?: string }[],
      {
        mathCount: subtopics.length,
        includeCharts: options.includeImages ?? true
      }
    )

    const response = await this.callLLM(prompt, options)
    const questions = this.parseQuestions(response, subtopics, 'math')
    console.log(`✅ Parsed ${questions.length} math questions`)
    return questions
  }

  /**
   * Generate reading questions using LLM
   */
  private async generateReadingQuestions(
    subtopics: EnrichedSubtopic[],
    options: GenerationOptions
  ): Promise<GeneratedQuestion[]> {
    if (subtopics.length === 0) return []

    console.log(`📚 Generating ${subtopics.length} reading questions...`)
    const prompt = buildReadingQuestionsPrompt(
      subtopics as unknown as { name: string; topicName?: string; description?: string }[],
      {
        readingCount: subtopics.length,
        includePassages: options.includePassages ?? true
      }
    )

    const response = await this.callLLM(prompt, options)
    const questions = this.parseQuestions(response, subtopics, 'reading-writing')
    console.log(`✅ Parsed ${questions.length} reading questions`)
    return questions
  }

  /**
   * Call LLM API (Azure OpenAI)
   */
  private async callLLM(prompt: string, options: GenerationOptions): Promise<string> {
    const endpoint = this.getChatEndpoint()
    const apiKey = this.getApiKey()

    if (!endpoint || !apiKey) {
      throw new Error('Missing Azure OpenAI config: set AZURE_OPENAI_API_KEY and ENDPOINT_URL or AZURE_OPENAI_ENDPOINT')
    }

    console.log(`🌐 Calling LLM at ${endpoint.substring(0, 50)}...`)

    // Build request body - some Azure OpenAI models have strict parameter requirements
    const requestBody: any = {
      messages: [
        {
          role: 'system',
          content: SYSTEM_ROLES.QUESTION_GENERATOR
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_completion_tokens: options.maxTokens || 16000  // Azure OpenAI requires max_completion_tokens for GPT-4o/newer models
    }
    
    // Only add temperature if explicitly set and not default (some models only support default temperature=1)
    // if (options.temperature && options.temperature !== 1) {
    //   requestBody.temperature = options.temperature
    // }

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'api-key': apiKey,
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(requestBody)
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error(`❌ LLM API Error: ${response.status} ${response.statusText}`)
      console.error(errorText)
      throw new Error(`LLM API error: ${response.status} ${response.statusText}`)
    }

    const data = await response.json()

    if (!data.choices?.[0]?.message?.content) {
      throw new Error('Invalid LLM response structure')
    }

    const content = data.choices[0].message.content
    console.log(`✅ LLM response: ${content.length} characters`)
    return content
  }

  /**
   * Parse LLM response into structured questions
   */
  private parseQuestions(
    response: string,
    subtopics: EnrichedSubtopic[],
    moduleType: 'math' | 'reading-writing'
  ): GeneratedQuestion[] {
    try {
      // Clean markdown code blocks
      let cleaned = response.trim()
      if (cleaned.startsWith('```json')) {
        cleaned = cleaned.slice(7)
      }
      if (cleaned.startsWith('```')) {
        cleaned = cleaned.slice(3)
      }
      if (cleaned.endsWith('```')) {
        cleaned = cleaned.slice(0, -3)
      }
      cleaned = cleaned.trim()

      const parsed = JSON.parse(cleaned)
      const questionsArray = Array.isArray(parsed) ? parsed : (parsed.questions || [])

      return questionsArray.map((q: Record<string, unknown>, index: number) => ({
        question: q.question || '',
        options: q.options || [],
        correctAnswer: typeof q.correctAnswer === 'number' ? q.correctAnswer : (typeof q.correct_answer === 'number' ? q.correct_answer : 0),
        explanation: q.explanation || '',
        subtopic: q.subtopic || subtopics[index]?.name || '',
        moduleType,
        hasChart: q.hasChart || q.has_chart || false,
        chartDescription: q.chartDescription || q.chart_description || '',
        graphType: q.graphType || q.graph_type || '',
        passage: q.passage || '',
        passageTitle: q.passageTitle || q.passage_title || '',
        passageAuthor: q.passageAuthor || q.passage_author || ''
      }))
    } catch (error) {
      console.error('❌ Failed to parse questions:', error)
      console.error('Response:', response.substring(0, 500))
      throw new Error('Failed to parse LLM response as JSON')
    }
  }

  // ==========================================================================
  // STEP 3: EVALUATE - GROK QUALITY SCORING
  // ==========================================================================

  /**
   * Evaluate all questions with Grok
   */
  private async evaluateQuestions(questions: GeneratedQuestion[]): Promise<EvaluatedQuestion[]> {
    console.log(`🔍 Evaluating ${questions.length} questions with Grok...`)

    const evaluated = await Promise.all(
      questions.map(q => this.evaluateQuestion(q))
    )

    const avgQuality = evaluated.reduce((sum, q) => sum + q.qualityScore, 0) / evaluated.length
    console.log(`✅ Evaluation complete: ${(avgQuality * 100).toFixed(1)}% average quality`)

    return evaluated
  }

  /**
   * Evaluate a single question with Grok (with fallback)
   */
  private async evaluateQuestion(question: GeneratedQuestion): Promise<EvaluatedQuestion> {
    try {
      const endpoint = this.getGrokEndpoint()
      const apiKey = this.getApiKey()

      if (!endpoint || !apiKey) {
        console.warn('⚠️  Grok endpoint not configured, using fallback evaluation')
        return this.fallbackEvaluation(question)
      }

      const evaluationPrompt = `Evaluate this SAT question on a scale of 0-100:

Question: ${question.question}
Options: ${question.options.join(', ')}
Correct Answer: ${question.correctAnswer}
Explanation: ${question.explanation}

Criteria:
1. Clarity and precision of question wording
2. Quality and plausibility of incorrect options
3. Accuracy and completeness of explanation
4. Alignment with SAT difficulty and format
5. Absence of errors or ambiguity

Respond in JSON format:
{
  "difficulty": "easy|medium|hard",
  "qualityScore": 85,
  "isAccepted": true,
  "evaluationFeedback": "Brief feedback"
}`

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'api-key': apiKey,
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          messages: [
            {
              role: 'system',
              content: SYSTEM_ROLES.EVALUATOR
            },
            {
              role: 'user',
              content: evaluationPrompt
            }
          ],
          max_completion_tokens: 1000  // Increased from 500 - evaluation responses need more tokens for complete JSON
          // Note: temperature removed - some models only support default value
        })
      })

      if (!response.ok) {
        const errorText = await response.text()
        console.warn(`⚠️  Grok evaluation failed (${response.status}): ${errorText.substring(0, 200)}`)
        return this.fallbackEvaluation(question)
      }

      const data = await response.json()
      const content = data.choices?.[0]?.message?.content

      if (!content) {
        console.warn(`⚠️  Grok response missing content. Response structure:`, JSON.stringify(data).substring(0, 200))
        return this.fallbackEvaluation(question)
      }

      console.log(`📊 Grok evaluation response (first 200 chars): ${content.substring(0, 200)}`)
      const evaluation = this.parseEvaluation(content)

      return {
        ...question,
        difficulty: evaluation.difficulty,
        qualityScore: evaluation.qualityScore / 100, // Normalize to 0-1
        isAccepted: evaluation.isAccepted,
        evaluationFeedback: evaluation.evaluationFeedback
      }
    } catch (error) {
      console.warn('⚠️  Grok evaluation error:', error)
      return this.fallbackEvaluation(question)
    }
  }

  /**
   * Parse Grok evaluation response
   */
  private parseEvaluation(response: string): {
    difficulty: 'easy' | 'medium' | 'hard'
    qualityScore: number
    isAccepted: boolean
    evaluationFeedback: string
  } {
    try {
      let cleaned = response.trim()
      if (cleaned.startsWith('```json')) cleaned = cleaned.slice(7)
      if (cleaned.startsWith('```')) cleaned = cleaned.slice(3)
      if (cleaned.endsWith('```')) cleaned = cleaned.slice(0, -3)
      cleaned = cleaned.trim()

      const parsed = JSON.parse(cleaned)

      return {
        difficulty: parsed.difficulty || 'medium',
        qualityScore: parsed.qualityScore || 75,
        isAccepted: parsed.isAccepted !== false,
        evaluationFeedback: parsed.evaluationFeedback || 'Evaluated by Grok'
      }
    } catch {
      console.warn('⚠️  Failed to parse evaluation, using defaults')
      return {
        difficulty: 'medium',
        qualityScore: 75,
        isAccepted: true,
        evaluationFeedback: 'Evaluation parse failed'
      }
    }
  }

  /**
   * Fallback evaluation when Grok is unavailable
   */
  private fallbackEvaluation(question: GeneratedQuestion): EvaluatedQuestion {
    console.log('📋 Using fallback evaluation')
    return {
      ...question,
      difficulty: 'medium',
      qualityScore: 0.75,
      isAccepted: true,
      evaluationFeedback: 'Fallback evaluation - Grok unavailable'
    }
  }

  // ==========================================================================
  // STEP 4: RETRY - REGENERATE LOW-QUALITY QUESTIONS (from Migration)
  // ==========================================================================

  /**
   * Retry low-quality questions (≤80% threshold)
   * Up to 5 regeneration attempts per question
   */
  private async retryLowQualityQuestions(
    questions: EvaluatedQuestion[],
    options: GenerationOptions
  ): Promise<{ questions: EvaluatedQuestion[]; retryCount: number }> {
    let retryCount = 0
    const threshold = QUALITY_THRESHOLDS.REGENERATION_THRESHOLD
    const maxAttempts = QUALITY_THRESHOLDS.MAX_REGENERATION_ATTEMPTS

    const retriedQuestions = await Promise.all(
      questions.map(async (question) => {
        if (question.qualityScore > threshold) {
          return question // Already acceptable
        }

        console.log(`🔄 Retrying low-quality question (${(question.qualityScore * 100).toFixed(0)}% ≤ ${(threshold * 100).toFixed(0)}%)`)
        
        let currentQuestion = question
        let attempts = 0
        let previousScores: number[] = []

        while (attempts < maxAttempts && currentQuestion.qualityScore <= threshold) {
          attempts++
          retryCount++

          try {
            // Regenerate the question
            const regenerated = await this.regenerateSingleQuestion(currentQuestion, options)
            
            // Re-evaluate
            const evaluated = await this.evaluateQuestion(regenerated)
            
            console.log(`  Attempt ${attempts}: Quality = ${(evaluated.qualityScore * 100).toFixed(0)}%`)

            // Check for plateau detection - if last 3 scores are identical, stop retrying
            previousScores.push(evaluated.qualityScore)
            if (previousScores.length >= 3) {
              const lastThree = previousScores.slice(-3)
              const allSame = lastThree.every(score => Math.abs(score - lastThree[0]) < 0.01) // Within 1%
              if (allSame) {
                console.log(`  ⏹️  Quality plateau detected (${(lastThree[0] * 100).toFixed(0)}% × 3), stopping retries`)
                return {
                  ...evaluated,
                  evaluationFeedback: `${evaluated.evaluationFeedback} (Quality plateau reached)`
                }
              }
            }

            if (evaluated.qualityScore > threshold) {
              console.log(`  ✅ Quality improved, accepting`)
              return evaluated
            }

            currentQuestion = evaluated
          } catch (error) {
            console.error(`  ❌ Retry attempt ${attempts} failed:`, error)
            break
          }
        }

        console.log(`  ⚠️  Max retries reached (${attempts}), accepting last attempt`)
        return {
          ...currentQuestion,
          evaluationFeedback: `${currentQuestion.evaluationFeedback} (Accepted after ${attempts} retries)`
        }
      })
    )

    console.log(`🔄 Retry summary: ${retryCount} total regeneration attempts`)
    return { questions: retriedQuestions, retryCount }
  }

  /**
   * Regenerate a single question using same parameters
   */
  private async regenerateSingleQuestion(
    question: EvaluatedQuestion,
    options: GenerationOptions
  ): Promise<GeneratedQuestion> {
    console.log(`  🔄 Regenerating ${question.moduleType} question for ${question.subtopic}`)

    const allSubtopics = getAllSubtopics()
    
    // Try exact match first
    let subtopic = allSubtopics.find(
      s => s.name.toLowerCase() === question.subtopic.toLowerCase() && s.moduleType === question.moduleType
    )
    
    // If no exact match, try matching without parentheses (e.g., "Main Ideas (Reading)" → "Main Ideas")
    if (!subtopic) {
      const cleanedQuestionSubtopic = question.subtopic.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase()
      subtopic = allSubtopics.find(
        s => s.name.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase() === cleanedQuestionSubtopic && 
             s.moduleType === question.moduleType
      )
    }
    
    // If still no match, try partial match (contains)
    if (!subtopic) {
      const cleanedQuestionSubtopic = question.subtopic.replace(/\s*\([^)]*\)/g, '').trim().toLowerCase()
      subtopic = allSubtopics.find(
        s => (s.name.toLowerCase().includes(cleanedQuestionSubtopic) || 
              cleanedQuestionSubtopic.includes(s.name.toLowerCase())) &&
             s.moduleType === question.moduleType
      )
    }

    if (!subtopic) {
      console.warn(`⚠️  Subtopic not found: "${question.subtopic}" - using fallback`)
      // Return original question if we can't find subtopic (better than crashing)
      return question
    }

    if (question.moduleType === 'math') {
      const questions = await this.generateMathQuestions([subtopic], options)
      return questions[0] || question
    } else {
      const questions = await this.generateReadingQuestions([subtopic], options)
      return questions[0] || question
    }
  }

  // ==========================================================================
  // STEP 5: VALIDATE - DIAGRAM CONSISTENCY CHECK (from Migration)
  // ==========================================================================

  /**
   * Validate diagram consistency: -40% penalty for questions mentioning diagrams without images
   */
  private async validateDiagramConsistency(questions: EvaluatedQuestion[]): Promise<EvaluatedQuestion[]> {
    console.log('🔍 Validating diagram consistency...')

    return questions.map(question => {
      // Only validate math questions
      if (question.moduleType !== 'math') {
        return question
      }

      const questionLower = question.question.toLowerCase()
      
      // More precise detection: look for phrases that indicate visual elements
      const diagramPhrases = [
        'in the diagram',
        'in the chart',
        'in the graph',
        'in the figure',
        'the diagram',
        'the chart',
        'the graph',
        'the figure',
        'coordinate plane',
        'shown in',
        'shown below',
        'shown above',
        'as shown',
        'illustrated in',
        'displayed in',
        'refers to the',
        'look at the'
      ]
      
      const mentionsDiagram = diagramPhrases.some(phrase => questionLower.includes(phrase))
      
      const hasImageUrl = !!question.imageUrl && question.imageUrl.length > 0
      const hasChartDescription = !!question.chartDescription && question.chartDescription.length > 10

      // CRITICAL ERROR: Question mentions diagram but has no image
      if (mentionsDiagram && !hasImageUrl) {
        console.log(`  ⚠️  CRITICAL: Question mentions diagram without image`)
        console.log(`     Question: "${question.question.substring(0, 60)}..."`)
        console.log(`     hasChart: ${question.hasChart}, imageUrl: ${hasImageUrl}, chartDesc: ${hasChartDescription}`)

        const newQualityScore = Math.max(0.3, question.qualityScore - 0.4) // -40% penalty

        return {
          ...question,
          qualityScore: newQualityScore,
          isAccepted: false,
          evaluationFeedback: `${question.evaluationFeedback} | CRITICAL ERROR: Question references diagram/chart that doesn't exist. Quality penalized from ${(question.qualityScore * 100).toFixed(0)}% to ${(newQualityScore * 100).toFixed(0)}%.`
        }
      }

      // ERROR: Has chart flag but no image generated
      if (question.hasChart && !hasImageUrl) {
        console.log(`  ⚠️  ERROR: Chart generation failed`)
        console.log(`     Question: "${question.question.substring(0, 60)}..."`)

        const newQualityScore = Math.max(0.4, question.qualityScore - 0.25) // -25% penalty

        return {
          ...question,
          qualityScore: newQualityScore,
          isAccepted: false,
          evaluationFeedback: `${question.evaluationFeedback} | ERROR: Chart/diagram generation failed. Quality penalized from ${(question.qualityScore * 100).toFixed(0)}% to ${(newQualityScore * 100).toFixed(0)}%.`
        }
      }

      // SUCCESS: Diagram mentioned and image exists
      if (mentionsDiagram && hasImageUrl) {
        console.log(`  ✅ Diagram consistency OK: "${question.question.substring(0, 60)}..."`)
      }

      return question
    })
  }

  // ==========================================================================
  // STEP 6: STORE - DATABASE PERSISTENCE WITH IMAGES
  // ==========================================================================

  /**
   * Store questions in database (with image generation)
   */
  private async storeQuestions(questions: EvaluatedQuestion[]): Promise<void> {
    console.log(`💾 Storing ${questions.length} questions in database...`)

    // First, generate images for questions that need them
    const questionsWithImages = await this.generateAndStoreImages(questions)

    // Then store in database
    for (const question of questionsWithImages) {
      try {
        const subtopic = getAllSubtopics().find(
          s => s.name.toLowerCase() === question.subtopic.toLowerCase()
        )

        if (!subtopic) {
          console.warn(`  ⚠️  Subtopic not found: ${question.subtopic}, skipping`)
          continue
        }

        await this.prisma.question.create({
          data: {
            question: question.question,
            options: JSON.stringify(question.options),
            correctAnswer: question.correctAnswer,
            explanation: question.explanation,
            moduleType: question.moduleType,
            difficulty: question.difficulty,
            subtopicId: subtopic.id,
            category: subtopic.topicName || '',
            subtopic: question.subtopic,
            chartData: question.hasChart ? JSON.stringify({
              description: question.chartDescription,
              graphType: question.graphType,
              hasChart: true
            }) : null,
            imageUrl: question.imageUrl || null,
            imageAlt: question.imageAlt || null,
            passage: question.passage || null,
            reviewStatus: question.isAccepted ? 'approved' : 'pending',
            reviewComments: `Quality score: ${(question.qualityScore * 100).toFixed(1)}%`,
            timeEstimate: 90, // Default 90 seconds
            source: 'AI Generated (Unified Service)',
            tags: JSON.stringify([question.moduleType, question.difficulty, question.subtopic]),
            isActive: true
          }
        })

        console.log(`  ✅ Stored: ${question.subtopic} (${(question.qualityScore * 100).toFixed(0)}% quality)`)
      } catch (error) {
        console.error(`  ❌ Failed to store question:`, error)
      }
    }

    console.log(`✅ Database storage complete`)
  }

  /**
   * Generate and store images for questions with chart descriptions
   */
  private async generateAndStoreImages(questions: EvaluatedQuestion[]): Promise<EvaluatedQuestion[]> {
    const questionsWithCharts = questions.filter(
      q => q.hasChart && q.chartDescription && q.moduleType === 'math'
    )

    console.log(`🎨 Generating images for ${questionsWithCharts.length} questions with charts...`)

    if (questionsWithCharts.length === 0) {
      return questions
    }

    // Dynamically import image service
    const { imageGenerationService } = await import('./imageGenerationService')

    const questionsWithImages = await Promise.all(
      questions.map(async (question) => {
        if (question.hasChart && question.chartDescription && question.moduleType === 'math') {
          try {
            console.log(`  🎨 Generating image for: "${question.question.substring(0, 50)}..."`)

            const chartConfig = {
              type: (question.graphType as 'coordinate-plane' | 'bar-chart' | 'scatter-plot' | 'box-plot' | 'geometric-diagram' | 'function-graph') || 'coordinate-plane',
              description: question.chartDescription,
              width: 600,
              height: 400
            }

            // Try DALL-E first
            let imageUrl = await imageGenerationService.generateChartImage(chartConfig)

            // Fallback to SVG if DALL-E fails
            if (!imageUrl) {
              console.log('    📋 DALL-E failed, generating SVG fallback...')
              imageUrl = await imageGenerationService.generateSVGChart(chartConfig)
            }

            if (imageUrl) {
              console.log(`    ✅ Image generated: ${imageUrl.substring(0, 80)}...`)
              return {
                ...question,
                imageUrl,
                imageAlt: question.chartDescription
              }
            } else {
              console.error(`    ❌ Image generation failed`)
              return question
            }
          } catch (error) {
            console.error('    ❌ Image generation error:', error)
            return question
          }
        }

        return question
      })
    )

    const successCount = questionsWithImages.filter(q => q.imageUrl).length
    console.log(`✅ Image generation complete: ${successCount}/${questionsWithCharts.length} successful`)

    return questionsWithImages
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export const unifiedQuestionGenerator = new UnifiedQuestionGenerator()
