/**
 * Import diagram batch JSON files into the DuckSAT database.
 * Reads batch files generated by generate_diagram_questions.py
 * and inserts questions with their diagram images into Azure SQL via Prisma.
 *
 * Usage:
 *   npx tsx scripts/import-diagram-batch.ts <batch-file.json>
 *   npx tsx scripts/import-diagram-batch.ts --all
 */

import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { PrismaClient } from '@prisma/client';
import { readFile, readdir } from 'fs/promises';
import { join, resolve } from 'path';

const prisma = new PrismaClient();

interface DiagramQuestion {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  wrongAnswerExplanations?: Record<string, string>;
  difficulty: string;
  category: string;
  subtopic: string;
  moduleType: string;
  visualType: string;
  diagram_description?: string;
  _imageBase64?: string;
  _imageMimeType?: string;
  _imageAlt?: string;
  _batchId?: string;
  _generatedAt?: string;
}

interface DiagramBatch {
  batchId: string;
  topic: string;
  moduleType: string;
  diagramType: string;
  generatedAt: string;
  totalValid: number;
  questions: DiagramQuestion[];
}

const DIFFICULTY_TIME: Record<string, number> = {
  easy: 60,
  medium: 90,
  hard: 120,
};

async function importBatch(filepath: string): Promise<{ imported: number; skipped: number; duplicates: number }> {
  const content = await readFile(filepath, 'utf-8');
  const batch: DiagramBatch = JSON.parse(content);

  console.log(`\n📦 Batch: ${batch.batchId}`);
  console.log(`   Type: ${batch.diagramType} | Questions: ${batch.questions.length}`);

  let imported = 0;
  let skipped = 0;
  let duplicates = 0;

  for (const q of batch.questions) {
    // Skip if missing image
    if (!q._imageBase64 || q._imageBase64.length < 200) {
      console.log(`   ⚠ Skipping - no diagram image`);
      skipped++;
      continue;
    }

    // Check for duplicates by question text (first 100 chars)
    const truncated = q.question.substring(0, 100);
    const existing = await prisma.question.findFirst({
      where: {
        question: { startsWith: truncated },
        isActive: true,
      },
      select: { id: true },
    });

    if (existing) {
      duplicates++;
      continue;
    }

    try {
      const imageBuffer = Buffer.from(q._imageBase64, 'base64');
      const options = Array.isArray(q.options) ? JSON.stringify(q.options) : q.options;
      const tags = JSON.stringify([
        q.category,
        q.subtopic,
        q.visualType,
        'has-diagram',
        `difficulty-${q.difficulty}`,
      ]);

      await prisma.question.create({
        data: {
          question: q.question,
          options: options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          difficulty: q.difficulty,
          category: q.category,
          subtopic: q.subtopic || 'general',
          moduleType: q.moduleType,
          timeEstimate: DIFFICULTY_TIME[q.difficulty] || 90,
          tags: tags,
          source: `diagram-gen-${batch.batchId}`,
          isActive: true,
          isReserved: false,
          imageData: imageBuffer,
          imageMimeType: q._imageMimeType || 'image/png',
          imageAlt: (q._imageAlt || q.diagram_description || 'Diagram')?.substring(0, 500),
          visualType: q.visualType,
        },
      });

      imported++;
    } catch (error: any) {
      console.log(`   ❌ Insert failed: ${error.message?.substring(0, 120)}`);
      skipped++;
    }
  }

  console.log(`   ✅ Imported: ${imported} | ⏭ Duplicates: ${duplicates} | ❌ Skipped: ${skipped}`);
  return { imported, skipped, duplicates };
}

async function main() {
  const args = process.argv.slice(2);
  const batchDir = resolve(__dirname, '..', 'generated-batches', 'diagram-batches');

  let files: string[] = [];

  if (args.includes('--all')) {
    const entries = await readdir(batchDir);
    files = entries
      .filter((f) => f.endsWith('.json'))
      .map((f) => join(batchDir, f));
    console.log(`📂 Found ${files.length} diagram batch files`);
  } else if (args.length > 0 && !args[0].startsWith('--')) {
    files = [resolve(args[0])];
  } else {
    console.log('Usage:');
    console.log('  npx tsx scripts/import-diagram-batch.ts <batch-file.json>');
    console.log('  npx tsx scripts/import-diagram-batch.ts --all');
    process.exit(1);
  }

  let totalImported = 0;
  let totalSkipped = 0;
  let totalDuplicates = 0;

  for (const f of files) {
    const result = await importBatch(f);
    totalImported += result.imported;
    totalSkipped += result.skipped;
    totalDuplicates += result.duplicates;
  }

  // Count current diagram questions
  const diagramCount = await prisma.question.count({
    where: { isActive: true, imageData: { not: null } },
  });
  const totalCount = await prisma.question.count({
    where: { isActive: true },
  });
  const pct = ((diagramCount / totalCount) * 100).toFixed(1);

  console.log(`\n${'═'.repeat(60)}`);
  console.log(`📊 IMPORT COMPLETE`);
  console.log(`${'═'.repeat(60)}`);
  console.log(`   Imported: ${totalImported}`);
  console.log(`   Duplicates: ${totalDuplicates}`);
  console.log(`   Skipped: ${totalSkipped}`);
  console.log(`\n📈 DATABASE STATUS:`);
  console.log(`   Total questions: ${totalCount}`);
  console.log(`   With diagrams: ${diagramCount} (${pct}%)`);
  console.log(`   Target: 25% → ${Math.ceil(totalCount * 0.25)} needed`);
  console.log(`   Remaining: ${Math.max(0, Math.ceil(totalCount * 0.25) - diagramCount)}`);
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
