"use client"

import { useState, useEffect, useCallback } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import Script from 'next/script'
import { ChevronLeft, ChevronRight, Filter, X } from 'lucide-react'
import { ADMIN_EMAILS } from '@/constants/adminEmails'

interface Question {
  id: string
  questionIndex?: number | null
  moduleType: string
  difficulty: string
  category: string
  subtopic: string | null
  question: string
  passage: string | null
  options: string[]
  correctAnswer: number
  explanation: string
  imageUrl?: string | null
  imageData?: string | null
  imageMimeType?: string | null
  chartData?: Record<string, unknown> | null
  reviewStatus: string | null
  reviewRating?: number | null
  diagramAccurate?: boolean | null
  reviewComments: string | null
  reviewedBy: string | null
  reviewedAt: string | null
  createdAt: string
  updatedAt: string
  subtopicRef?: {
    name: string
  }
}

interface Pagination {
  page: number
  limit: number
  total: number
  pages: number
}

export default function EnhancedQuestionsReview() {
  const { data: session, status } = useSession()
  const router = useRouter()

  const [questions, setQuestions] = useState<Question[]>([])
  const [pagination, setPagination] = useState<Pagination | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [currentPage, setCurrentPage] = useState(1)
  const [statusFilter, setStatusFilter] = useState<string>('')
  const [categoryFilter, setCategoryFilter] = useState<string>('')
  const [subtopicFilter, setSubtopicFilter] = useState<string>('')
  const [diagramOnly, setDiagramOnly] = useState<boolean>(false)
  const [searchText, setSearchText] = useState<string>('')
  const [mathJaxLoaded, setMathJaxLoaded] = useState(false)
  const [deletingAutoGenerated, setDeletingAutoGenerated] = useState<boolean>(false)
  const [deleteResult, setDeleteResult] = useState<number | null>(null)
  const [indexDrafts, setIndexDrafts] = useState<Record<string, string>>({})
  const [savingIndexId, setSavingIndexId] = useState<string | null>(null)

  // Render LaTeX content
  const renderLatex = (text: string) => {
    return text
  }

  // Trigger MathJax to process content
  useEffect(() => {
    if (typeof window !== 'undefined' && (window as { MathJax?: { typesetPromise?: () => Promise<void> } }).MathJax && mathJaxLoaded && questions.length > 0) {
      ; (window as { MathJax?: { typesetPromise?: () => Promise<void> } }).MathJax?.typesetPromise?.().catch((err: Error) => console.error('MathJax error:', err))
    }
  }, [questions, mathJaxLoaded])

  // Format image data URL
  const getImageDataUrl = (question: Question) => {
    if (question.imageData) {
      if (question.imageData.startsWith('data:')) {
        return question.imageData
      }
      const mimeType = question.imageMimeType || 'image/png'
      return `data:${mimeType};base64,${question.imageData}`
    }
    return question.imageUrl
  }

  const fetchQuestions = useCallback(async (page = 1) => {
    setLoading(true)
    setError(null)

    try {
      const params = new URLSearchParams({
        page: page.toString(),
        limit: '20'
      })

      if (statusFilter) params.append('status', statusFilter)
      if (categoryFilter) params.append('category', categoryFilter)
      if (subtopicFilter) params.append('subtopic', subtopicFilter)
      if (diagramOnly) params.append('hasDiagram', 'true')

      const response = await fetch(`/api/admin/questions?${params}`)
      if (!response.ok) {
        throw new Error('Failed to fetch questions')
      }

      const data = await response.json()
      // options and chartData are stored as JSON strings in the DB; parse them
      const parsed = data.questions.map((q: Question & { options: string | string[]; chartData: string | Record<string, unknown> | null }) => ({
        ...q,
        options: typeof q.options === 'string' ? JSON.parse(q.options) : (q.options ?? []),
        chartData: typeof q.chartData === 'string' ? JSON.parse(q.chartData) : q.chartData
      }))
      setQuestions(parsed)
      setPagination(data.pagination)
      setCurrentPage(page)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }, [statusFilter, categoryFilter, subtopicFilter, diagramOnly])

  useEffect(() => {
    const userEmail = session?.user?.email || '';
    const isAdmin = ADMIN_EMAILS.includes(userEmail);
    if (status === 'authenticated' && isAdmin) {
      fetchQuestions()
    }
  }, [status, session, fetchQuestions])

  // Filter questions by search text and diagram toggle
  const filteredQuestions = questions
    .filter(q => !diagramOnly || !!(q.imageData || q.imageUrl))
    .filter(q => {
      if (!searchText.trim()) return true
      const text = [q.question, q.passage, ...(q.options || [])].join(' ').toLowerCase()
      return text.includes(searchText.toLowerCase())
    })

  const handleDeleteAutoGenerated = async () => {
    const confirmed = window.confirm(
      "This will permanently delete all questions containing 'auto-generated'. This action cannot be undone. Continue?"
    )
    if (!confirmed) return

    setDeletingAutoGenerated(true)
    setDeleteResult(null)
    setError(null)

    try {
      const response = await fetch('/api/admin/questions?filter=auto-generated', {
        method: 'DELETE'
      })
      if (!response.ok) throw new Error('Failed to delete questions')
      const data = await response.json()
      setDeleteResult(data.deleted)
      fetchQuestions(1)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete questions')
    } finally {
      setDeletingAutoGenerated(false)
    }
  }

  const handleSaveQuestionIndex = async (questionId: string) => {
    const draft = indexDrafts[questionId]
    const parsed = draft === undefined || draft.trim() === '' ? null : Number.parseInt(draft, 10)

    if (parsed !== null && (!Number.isInteger(parsed) || parsed < 1)) {
      setError('Question index must be a positive integer or blank')
      return
    }

    setSavingIndexId(questionId)
    setError(null)

    try {
      const response = await fetch(`/api/admin/questions/${questionId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ questionIndex: parsed })
      })

      if (!response.ok) {
        throw new Error('Failed to update question index')
      }

      const data = await response.json()
      setQuestions(prev => prev.map(q => q.id === questionId ? { ...q, questionIndex: data.question.questionIndex } : q))
      setIndexDrafts(prev => {
        const next = { ...prev }
        delete next[questionId]
        return next
      })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update question index')
    } finally {
      setSavingIndexId(null)
    }
  }

  if (status === 'loading') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-indigo-600 mx-auto"></div>
          <p className="mt-6 text-xl text-gray-700 font-medium">Loading...</p>
        </div>
      </div>
    )
  }

  const userEmail = session?.user?.email || '';
  const isAdmin = ADMIN_EMAILS.includes(userEmail);
  if (!isAdmin) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-50 to-orange-50 flex items-center justify-center">
        <div className="text-center bg-white p-12 rounded-3xl shadow-2xl">
          <div className="text-6xl mb-6">🚫</div>
          <h1 className="text-3xl font-bold text-red-600 mb-4">Access Denied</h1>
          <p className="text-gray-600 text-lg">You don&apos;t have permission to access this page.</p>
        </div>
      </div>
    )
  }

  const totalQuestions = pagination?.total || 0

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50">
      {/* Back to Home button */}
      <div className="fixed left-4 top-4 z-50">
        <button
          onClick={() => router.push('/')}
          className="bg-white/90 border border-gray-200 shadow px-4 py-2 rounded-xl font-semibold text-gray-700 hover:bg-gray-100 hover:shadow-md transition-all"
        >
          🏠 Back to Home
        </button>
      </div>
      <Script
        id="mathjax-config"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.MathJax = {
              tex: {
                inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
                displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],
                processEscapes: true,
                processEnvironments: true
              },
              options: {
                skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre']
              },
              startup: {
                pageReady: () => {
                  return window.MathJax.startup.defaultPageReady().then(() => {
                    console.log('MathJax initial typesetting complete');
                  });
                }
              }
            };
          `
        }}
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        strategy="afterInteractive"
        onLoad={() => setMathJaxLoaded(true)}
      />

      {/* Enhanced Header with Gradient */}
      <div className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 shadow-2xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <div className="flex justify-between items-center mb-10">
            <div>
              <h1 className="text-5xl md:text-6xl font-extrabold text-white flex items-center gap-4">
                <span className="text-6xl md:text-7xl">📝</span>
                Question Manager
              </h1>
              <p className="mt-4 text-xl md:text-2xl text-indigo-100">
                Browse, search, and manage all SAT questions in the database
              </p>
            </div>
            <button
              onClick={() => router.push('/admin')}
              className="hidden md:flex items-center gap-2 bg-white/20 backdrop-blur-lg text-white px-6 py-3 rounded-xl font-bold hover:bg-white/30 transition-all duration-200 border border-white/30 shadow-lg hover:shadow-xl hover:scale-105"
            >
              <ChevronLeft size={20} />
              Back
            </button>
          </div>

          {/* Stats */}
          <div className="inline-flex bg-white/10 backdrop-blur-lg rounded-2xl px-8 py-5 border border-white/20">
            <div>
              <p className="text-white/80 text-sm font-medium uppercase tracking-wide">Total Questions</p>
              <p className="text-5xl font-bold text-white mt-2">{totalQuestions}</p>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Global Search Bar */}
        <div className="mb-8 flex flex-col md:flex-row items-center gap-4">
          <input
            type="text"
            value={searchText}
            onChange={e => setSearchText(e.target.value)}
            placeholder="Search questions, passages, or options..."
            className="w-full md:w-1/2 px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-4 focus:ring-indigo-200 focus:border-indigo-500 transition-all font-medium"
          />
          {searchText && (
            <button
              onClick={() => setSearchText('')}
              className="ml-2 px-4 py-2 bg-gray-100 text-gray-700 rounded-xl font-semibold hover:bg-gray-200 transition-all"
            >
              Clear
            </button>
          )}
        </div>
        <div className="flex flex-col lg:flex-row gap-8">
          {/* Sidebar Filters */}
          <div className="lg:w-1/4">
            <div className="bg-white rounded-3xl shadow-2xl p-6 sticky top-8 border border-gray-100">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                  <Filter size={24} className="text-indigo-600" />
                  Filters
                </h2>
              </div>

              <div className="space-y-5">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Status</label>
                  <select
                    value={statusFilter}
                    onChange={(e) => setStatusFilter(e.target.value)}
                    className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-4 focus:ring-indigo-200 focus:border-indigo-500 transition-all font-medium"
                  >
                    <option value="">All Statuses</option>
                    <option value="pending">⏳ Pending</option>
                    <option value="approved">✅ Approved</option>
                    <option value="rejected">❌ Rejected</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Category</label>
                  <select
                    value={categoryFilter}
                    onChange={(e) => setCategoryFilter(e.target.value)}
                    className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-4 focus:ring-indigo-200 focus:border-indigo-500 transition-all font-medium"
                  >
                    <option value="">All Categories</option>
                    <option value="reading-comprehension">📖 Reading</option>
                    <option value="writing">✍️ Writing</option>
                    <option value="algebra">🔢 Algebra</option>
                    <option value="geometry">📐 Geometry</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Subtopic</label>
                  <input
                    type="text"
                    value={subtopicFilter}
                    onChange={(e) => setSubtopicFilter(e.target.value)}
                    placeholder="Search subtopic..."
                    className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:ring-4 focus:ring-indigo-200 focus:border-indigo-500 transition-all font-medium"
                  />
                </div>

                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Diagram</label>
                  <button
                    onClick={() => setDiagramOnly(prev => !prev)}
                    className={`w-full px-4 py-3 rounded-xl font-bold text-sm border-2 transition-all ${
                      diagramOnly
                        ? 'bg-indigo-600 text-white border-indigo-600 shadow-md'
                        : 'bg-white text-gray-700 border-gray-200 hover:border-indigo-400'
                    }`}
                  >
                    {diagramOnly ? '📊 With Diagram ✓' : '📊 Show All'}
                  </button>
                </div>

                <button
                  onClick={() => fetchQuestions(1)}
                  className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-6 py-4 rounded-xl font-bold text-lg hover:from-indigo-700 hover:to-purple-700 transition-all shadow-lg hover:shadow-2xl hover:scale-105 transform"
                >
                  Apply Filters
                </button>

                {(statusFilter || categoryFilter || subtopicFilter || diagramOnly) && (
                  <button
                    onClick={() => {
                      setStatusFilter('')
                      setCategoryFilter('')
                      setSubtopicFilter('')
                      setDiagramOnly(false)
                    }}
                    className="w-full bg-gray-100 text-gray-700 px-6 py-3 rounded-xl font-semibold hover:bg-gray-200 transition-all flex items-center justify-center gap-2"
                  >
                    <X size={18} />
                    Clear Filters
                  </button>
                )}
              </div>

              {/* Danger Zone */}
              <div className="mt-6 border-2 border-red-200 rounded-2xl p-5 bg-red-50">
                <h3 className="text-base font-bold text-red-700 mb-2 flex items-center gap-2">
                  ⚠️ Danger Zone
                </h3>
                <p className="text-xs text-red-600 mb-4">
                  Permanently deletes all questions containing &ldquo;auto-generated&rdquo; in their text.
                </p>
                <button
                  onClick={handleDeleteAutoGenerated}
                  disabled={deletingAutoGenerated}
                  className="w-full bg-red-600 text-white px-4 py-3 rounded-xl font-bold text-sm hover:bg-red-700 disabled:opacity-50 transition-all shadow"
                >
                  {deletingAutoGenerated ? '🗑️ Deleting...' : '🗑️ Delete Auto-Generated'}
                </button>
                {deleteResult !== null && (
                  <p className="mt-3 text-sm font-semibold text-green-700 bg-green-50 border border-green-200 rounded-lg px-3 py-2">
                    ✅ Deleted {deleteResult} question{deleteResult !== 1 ? 's' : ''}
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="lg:w-3/4">
            {/* Error Display */}
            {error && (
              <div className="bg-gradient-to-r from-red-50 to-rose-50 border-2 border-red-200 rounded-3xl p-6 mb-8 shadow-xl">
                <div className="flex items-center space-x-4">
                  <div className="text-4xl">❌</div>
                  <div>
                    <h3 className="text-2xl font-bold text-red-800">Error</h3>
                    <p className="text-red-700 mt-1 text-lg">{error}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Questions List */}
            {loading ? (
              <div className="bg-white rounded-3xl shadow-2xl p-12">
                <div className="text-center">
                  <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-indigo-600 mx-auto"></div>
                  <p className="mt-6 text-xl text-gray-600 font-medium">Loading questions...</p>
                </div>
              </div>
            ) : filteredQuestions.length === 0 ? (
              <div className="bg-white rounded-3xl shadow-2xl p-16 text-center">
                <div className="text-8xl mb-6">🔍</div>
                <h3 className="text-3xl font-bold text-gray-900 mb-4">No Questions Found</h3>
                <p className="text-xl text-gray-600">Try adjusting your filters or search to see more results.</p>
              </div>
            ) : (
              <div className="space-y-6">
                {filteredQuestions.map((question) => (
                  <div key={question.id} className="bg-white rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-300 p-8 border-2 border-gray-100 hover:border-indigo-200 transform hover:scale-[1.02]">
                    <div className="flex items-start justify-between mb-6">
                      <div className="flex flex-wrap items-center gap-3">
                        <div className="flex items-center gap-2 bg-indigo-50 border border-indigo-200 px-3 py-2 rounded-full">
                          <span className="text-xs font-bold text-indigo-700 uppercase tracking-wide">Index</span>
                          <input
                            type="number"
                            min={1}
                            value={indexDrafts[question.id] ?? (question.questionIndex?.toString() ?? '')}
                            onChange={(e) => setIndexDrafts(prev => ({ ...prev, [question.id]: e.target.value }))}
                            className="w-16 px-2 py-1 rounded border border-indigo-300 text-xs font-bold text-indigo-900 bg-white"
                            placeholder="-"
                          />
                          <button
                            onClick={() => handleSaveQuestionIndex(question.id)}
                            disabled={savingIndexId === question.id}
                            className="text-xs font-bold px-2 py-1 rounded bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50"
                          >
                            {savingIndexId === question.id ? '...' : 'Save'}
                          </button>
                        </div>
                        {/* Question ID Badge */}
                        <button
                          onClick={() => navigator.clipboard.writeText(question.id)}
                          title={`Click to copy full ID: ${question.id}`}
                          className="font-mono text-xs bg-gray-100 text-gray-500 px-3 py-1 rounded-full border border-gray-300 hover:bg-indigo-50 hover:text-indigo-700 hover:border-indigo-300 transition-all cursor-copy"
                        >
                          ID: {question.id.slice(0, 8)}&hellip;
                        </button>
                        <span className={`px-4 py-2 rounded-full text-sm font-bold uppercase tracking-wide shadow-md ${question.moduleType === 'math' ? 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white' : 'bg-gradient-to-r from-purple-500 to-pink-500 text-white'
                          }`}>
                          {question.moduleType}
                        </span>
                        <span className={`px-4 py-2 rounded-full text-sm font-bold uppercase tracking-wide shadow-md ${question.difficulty === 'easy' ? 'bg-gradient-to-r from-green-400 to-emerald-500 text-white' :
                            question.difficulty === 'medium' ? 'bg-gradient-to-r from-yellow-400 to-orange-400 text-white' :
                              'bg-gradient-to-r from-red-500 to-rose-600 text-white'
                          }`}>
                          {question.difficulty}
                        </span>
                        <span className="text-sm text-gray-700 font-bold bg-gray-100 px-4 py-2 rounded-full">{question.category}</span>
                      </div>

                    </div>

                    {/* Passage */}
                    {question.passage && (
                      <div className="mb-6 p-6 bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl border-2 border-gray-200">
                        <h4 className="font-bold text-gray-900 mb-3 text-lg uppercase tracking-wide">📖 Passage</h4>
                        <p className="text-gray-800 whitespace-pre-wrap leading-relaxed text-lg">{question.passage}</p>
                      </div>
                    )}

                    {/* Question */}
                    <div className="mb-6">
                      <h4 className="font-bold text-gray-900 mb-3 text-lg uppercase tracking-wide">❓ Question</h4>
                      <div
                        className="text-gray-900 text-xl leading-relaxed"
                        dangerouslySetInnerHTML={{ __html: renderLatex(question.question) }}
                      />
                    </div>

                    {/* Diagram Display */}
                    {(question.imageData || question.imageUrl) && (
                      <div className="mb-6">
                        <h4 className="font-bold text-gray-900 mb-3 text-lg uppercase tracking-wide">📊 Diagram</h4>
                        <div className="border-2 border-gray-200 rounded-2xl p-6 bg-white flex justify-center shadow-inner">
                          {/* eslint-disable-next-line @next/next/no-img-element */}
                          <img
                            src={getImageDataUrl(question) || undefined}
                            alt="Question diagram"
                            className="max-w-full h-auto max-h-96 rounded-xl shadow-md"
                          />
                        </div>
                        {/* Diagram URL display */}
                        {question.imageUrl && (
                          <div className="mt-3 flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-xl px-4 py-2">
                            <span className="text-xs font-bold text-blue-700 uppercase tracking-wide flex-shrink-0">
                              🔗 Diagram URL:
                            </span>
                            <a
                              href={question.imageUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              title={question.imageUrl}
                              className="text-blue-600 text-sm underline truncate hover:text-blue-800 transition-colors"
                            >
                              {question.imageUrl.length > 70
                                ? question.imageUrl.slice(0, 70) + '\u2026'
                                : question.imageUrl}
                            </a>
                          </div>
                        )}
                        {question.chartData && (question.chartData as { description?: string }).description && (
                          <p className="text-sm text-gray-600 mt-3 bg-gray-50 p-4 rounded-xl border border-gray-200 italic">
                            <strong>Description:</strong> {(question.chartData as { description?: string }).description}
                          </p>
                        )}
                      </div>
                    )}

                    {/* Options */}
                    <div className="mb-6">
                      <h4 className="font-bold text-gray-900 mb-3 text-lg uppercase tracking-wide">📋 Answer Choices</h4>
                      <div className="space-y-3">
                        {question.options.map((option, index) => (
                          <div key={index} className={`p-4 rounded-2xl border-2 transition-all duration-200 ${index === question.correctAnswer
                              ? 'bg-gradient-to-r from-green-50 to-emerald-50 border-green-400 shadow-md'
                              : 'bg-white border-gray-200 hover:border-gray-300 hover:shadow-md'
                            }`}>
                            <div className="flex gap-4 items-start">
                              <span className={`flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-full text-sm font-bold ${index === question.correctAnswer ? 'bg-green-500 text-white shadow-lg' : 'bg-gray-200 text-gray-700'
                                }`}>
                                {String.fromCharCode(65 + index)}
                              </span>
                              <div className="flex-grow">
                                <span
                                  className="text-gray-900 text-lg"
                                  dangerouslySetInnerHTML={{ __html: renderLatex(option) }}
                                />
                                {index === question.correctAnswer && (
                                  <span className="ml-3 text-green-600 font-bold text-sm">✓ CORRECT ANSWER</span>
                                )}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Explanation */}
                    <div className="mb-6">
                      <h4 className="font-bold text-gray-900 mb-3 text-lg uppercase tracking-wide">💡 Explanation</h4>
                      <div className="bg-gradient-to-br from-blue-50 to-indigo-50 p-6 rounded-2xl border-2 border-blue-200">
                        <div
                          className="text-gray-800 leading-relaxed text-lg"
                          dangerouslySetInnerHTML={{ __html: renderLatex(question.explanation) }}
                        />
                      </div>
                    </div>


                  </div>
                ))}
              </div>
            )}

            {/* Pagination */}
            {pagination && pagination.pages > 1 && (
              <div className="mt-10 flex justify-center items-center gap-4">
                <button
                  onClick={() => fetchQuestions(currentPage - 1)}
                  disabled={currentPage === 1}
                  className="bg-white px-6 py-3 rounded-xl font-bold text-gray-700 hover:bg-indigo-100 disabled:opacity-30 disabled:cursor-not-allowed transition-all shadow-lg hover:shadow-xl flex items-center gap-2"
                >
                  <ChevronLeft size={20} />
                  Previous
                </button>

                <span className="bg-white px-6 py-3 rounded-xl font-bold text-gray-900 shadow-lg">
                  Page {currentPage} of {pagination.pages}
                </span>

                <button
                  onClick={() => fetchQuestions(currentPage + 1)}
                  disabled={currentPage === pagination.pages}
                  className="bg-white px-6 py-3 rounded-xl font-bold text-gray-700 hover:bg-indigo-100 disabled:opacity-30 disabled:cursor-not-allowed transition-all shadow-lg hover:shadow-xl flex items-center gap-2"
                >
                  Next
                  <ChevronRight size={20} />
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
